### ISSUE TITLE
Multiple byte formatting libraries

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1038]
## Issue
Multiple packages have been imported for formatting bytes for human readability.  We only need one.
* connector/status: `"github.com/inhies/go-bytesize"`
* details/details: `"github.com/dustin/go-humanize"`

## Effort, Value, Impact
Effort: zero  
Value: minimal  
Impact: minimal

**Comment by dadams39** [comment]
Closed by #2363
