### ISSUE TITLE
establish*RestoreLocation `isNewCache` check placement

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1201]
## Issue
When restoring to an existing folder, the `isNewCache` check within the `establish*RestoreLocation` funcs occurs after an attempted folder creation.  This can lead to unnecessary errors when the folder already exists.

## Acceptance Criteria
Move the `isNewCache` handling above folder creation.

**Comment by dadams39** [comment]
After a lengthy discussion, the change to the container resolvers would make the mail-resolver less efficient. Changes to placement will be updated when the restore policy is changed.
