### ISSUE TITLE
Selectors: match folder by parentRef entry

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1216]
## Issue
Much like how items can be selected in `details` and `restore` commands by either the itemID or the shortRef value, folders should be accessible by either the folder name or the parentRef property.

## Acceptance criteria
Within the selector reduction path processor, add `parentRef` comparison for non-root, non-leaf categories.  Comparison should use a logical _or_ to match on either the folder name (current handling) or full equality on the parentRef.

**Comment by ashmrtn** [comment]
Filling in some more details: from out of band discussion with some other folks it sounds like giving a folder reference should behave like giving a folder name in the sense that it should do prefix matching on the path the folder represents
