### ISSUE TITLE
User data in log output

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#1229]
Currently there's no standard for what data is allowed in logs and what is not. This leads to some log messages that has data which could be considered sensitive. This is data such as folder names, user names, etc.

A standard for what data is allowed to be logged should be made and log output should be scrubbed/logging calls updated to reflect that

**Comment by ryanfkeepers** [comment]
closing, work to be done in https://github.com/alcionai/corso/issues/2024
