### ISSUE TITLE
Test  release artifacts

### ISSUE THREAD

**Issue by meain** [alcionai/corso#1283]
Testing with `v0.0.1` artifacts.
- Binary
  - [x] Linux amd64
  - [x] Linux arm64
  - [x] Darwin amd64
  - [x] Darwin arm64
  - [x] Windows amd64
- Images
  - [x]  Linux amd64
  - [x] Linux arm64

**Comment by meain** [comment]
I've verified all the release artifacts apart from the `darwin` ones.

**Comment by vkamra** [comment]
Verified Mac binaries
