### ISSUE TITLE
Expose more information about the backed up items

### ISSUE THREAD

**Issue by rajatkateja** [alcionai/corso#1366]
In addition to the already present information in `ItemInfo, it would be useful to have the following information about the backed up items. 

Across all items:

- createdDateTime 
- modifiedDateTime
- accessedDateTime
- size (i.e., the actual size of the item)
- storedSize (i.e., how much space does this item take in the backup)

For OneDriveItem type
- owner

For ExchangeEvent type:
- eventDuration

For the common information, happy to discuss any nuances, e.g., some that I can think of: 
- for received emails, created and modified date times be same as received date time. same for accessed date time (unless there is some way to know when a user opens an email)
- for drafts, there can be separate created and modified date times? Although I wonder what is the received date time for drafts?
- for contacts, events, not sure what the accessed date time should be
- for folders, the size and storedSize should be the aggregate of their entries.

**Comment by vkamra** [comment]
@meain - should start with OneDrive (owner) (see https://github.com/alcionai/corso/blob/main/src/internal/connector/onedrive/item.go#L69) for how OneDriveInfo is populated. 

This information can then be viewed via the `corso backup details onedrive --backup <id>` command

**Comment by meain** [comment]
Maybe I'm missing something. I could not find the `backup details` command is hitting the function that you mentioned. I was able to track it down to https://github.com/alcionai/corso/blob/b5a274600818a075a48f862c7430769fcebad1fc/src/internal/kopia/model_store.go#L337 for loading which looks like it is doing a `json.Unmarshal` directly from kopia. I'm looking to how/where that information gets saved into kopia in the first place.

**Comment by ashmrtn** [comment]
Some links/execution flow to fill in the missing pieces for storing the data:

* Kopia Wrapper is requesting the item info during a backup [here](https://github.com/alcionai/corso/blob/b5a274600818a075a48f862c7430769fcebad1fc/src/internal/kopia/wrapper.go#L338). It adds it to a temp buffer, waits for the item to be uploaded to kopia completely, and then [adds](https://github.com/alcionai/corso/blob/b5a274600818a075a48f862c7430769fcebad1fc/src/internal/kopia/wrapper.go#L197) it to the `details.Details` struct in a callback that kopia exposes

* The complete set of details is [returned](https://github.com/alcionai/corso/blob/b5a274600818a075a48f862c7430769fcebad1fc/src/internal/operations/backup.go#L161) from KopiaWrapper to the backup operation when the backup is complete

* The backup operation then [saves](https://github.com/alcionai/corso/blob/b5a274600818a075a48f862c7430769fcebad1fc/src/internal/operations/backup.go#L221) the `details.Details` to the model store where they can be accessed later

* Models are serialized into JSON and stored in kopia (kopia does the struct -> JSON serialization internally) using the [model store](https://github.com/alcionai/corso/blob/b5a274600818a075a48f862c7430769fcebad1fc/src/internal/kopia/model_store.go#L135) in corso

I think it should be possible to update the information persisted in `details.Details` without needing to dig into the code I linked though. KopiaWrapper treats the item info as an opaque struct. It just moves the bytes around so they get persisted properly

**Comment by vkamra** [comment]
> Maybe I'm missing something. I could not find the `backup details` command is hitting the function that you mentioned. I was able to track it down to

@meain - @ashmrtn 's explanation above has more information. The function I had mentioned is where we return the metadata for each item being backed up which is persisted in the `details.Details` model for each Backup. If you add more information there.

**Comment by meain** [comment]
Thanks @ashmrtn , the pointers really came in handy. @vkamra , it does hit the function you pointed to but somehow the debugger stepped around it when I was trying out earlier.

I was able to get the owner info persisted into the store, but I was wondering what exact details should we be storing? As of now, I'm thinking display name, but should we store some kind of id and then lookup the name when displaying(in case they change the name)?

**Comment by vkamra** [comment]
Let's use the owner email for now

**Comment by meain** [comment]
For exchange, should we store event duration or just the end time as we are already storing the start time?

**Comment by meain** [comment]
I have a draft PR available at https://github.com/alcionai/corso/pull/1436. I'm trying to add an integration test for Owner in OneDrive by checking for `itemInfo.Owner` [here](https://github.com/alcionai/corso/blob/2ad9eb531c10eb7b38adc0239fd955bb4004143f/src/internal/connector/onedrive/item_test.go#L84), but it seems to be returning empty. Looking into what might be causing that.

**Comment by meain** [comment]
Should we add a flag for full day events? The event duration would be 24h otherwise. Also, [should we be storing end time instead of duration](https://github.com/alcionai/corso/issues/1366#issuecomment-1301992506)?
/cc @rajatkateja @vkamra

**Comment by rajatkateja** [comment]
Regarding events, I think the end time should also be fine. 

(I might be missing the context, but I am not sure why we would need a flag for 24 hours specifically though, events can be even longer than that, right?)

**Comment by meain** [comment]
> (I might be missing the context, but I am not sure why we would need a flag for 24 hours specifically though, events can be even longer than that, right?)
My bad events could be >24h, but there is a special marker for full day events for things like holidays. I was wondering if that would be useful.

**Comment by vkamra** [comment]
For now - I'd skip that. We'll see what feedback we get (i.e. what information would be useful for folks to use as a filter) and then go from there.

**Comment by meain** [comment]
@vkamra As of now, I'm not adding any new cli flags(for details, eg: `--event-starts-after`) for filtering by the new data that is available. Let me know if those are to be added.

**Comment by meain** [comment]
Looking at docs for [drive item](https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0), [mail](https://learn.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0), [contacts](https://learn.microsoft.com/en-us/graph/api/resources/contact?view=graph-rest-1.0) and [events](https://learn.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0), none of them seem to expose anything that we can use for "last accessed" time. They all however have both created and updated timestamps in the api. I've added them in https://github.com/alcionai/corso/pull/1452 . Let me know if we should consider anything specific in them for "last accessed" or if we should consider skipping that.

**Comment by meain** [comment]
What would be "size" for contacts, mail and events. There is nothing specific reported from the graph API. Would this be the size of the JSON api response?

**Comment by dadams39** [comment]
For `contacts`, `mail` or `events`, there's no API call to determine the size of the object. This is due to Graph not keeping all the fields populated with these objects. If you want to be able to access the size of `exchange` objects, I would suggest altering: `src/pkg/backup/details/details.go` for these objects and allow for the size, `len(bytes)` to be passed into `Info` object upon creation.

**Comment by meain** [comment]
I'm still wondering what exactly should be the `bytes` in the `len(bytes)`. Should we assume the full object, for example in case of contacts, will the size be the graph api response which includes the contact, and all related metadata or should be just the actual contact information.

**Comment by meain** [comment]
There is now just two more items left, but I'm not certain how/if we are proceeding with it.
- `storedSize`: Cannot get this info from kopia
- `accessedDateTime`: Unless we are duplicating info stored in other fields, there is no usable data for any object

**Comment by rajatkateja** [comment]
Thanks Abin! I think we can live without `accessedDateTime`, but I will defer to @gmatev. 
We will almost certain need `storedSize`.

**Comment by gmatev** [comment]
If accesedDateTime does not make sense for a data type we can skip it

On Nov 9, 2022 09:40, Rajat Kateja ***@***.***> wrote:

Thanks Abin! I think we can live without accessedDateTime, but I will defer to @gmatev<https://github.com/gmatev>.
We will almost certain need storedSize.

**Comment by meain** [comment]
Closing this as of now as we are not able to get per file size info from Kopia ATM.
