### ISSUE TITLE
Support for local storage

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso#1416]
for even easier evaluation allow using local storage for a test repo:

```
mkdir -p ~/.corso/repo

corso repo init filesystem --path ~/.corso/repo
corso repo connect filesystem --path ~/.corso/repo
```

Should be straightforward passthrough to Kopia https://kopia.io/docs/repositories/#local-or-network-attached-storage

**Comment by vkamra** [comment]
This is done. https://corsobackup.io/docs/setup/repos/#filesystem-storage
