### ISSUE TITLE
Test User Configuration: Calendar Misalignment

### ISSUE THREAD

**Issue by dadams39** [alcionai/corso#1500]
Changes made within PowerShell cause `Test_User_1`'s Calendar queries to not show new Calendars. Further investigation required.

**Comment by dadams39** [comment]
Configuration results in the following test failure:
`TestGraphConnectorIntegrationSuite/TestRestoreAndBackup/MultipleEventsSingleCalendar`

**Comment by meain** [comment]
Running `TestGraphConnectorIntegrationSuite/TestMultiuserRestoreAndBackup/Events` errors out with incorrect items for _just_ the lidiah test user. From what I could find, it comes down to graph api not returning any of the new calendars as mentioned above in the following query:
https://github.com/alcionai/corso/blob/c8362e96380087e60be6a04d514cd0433c5e9e56/src/internal/connector/exchange/event_calendar_cache.go#L48
