### ISSUE TITLE
pwsh script to remove test-generated onedrive files/folders

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1525]
Our purge scripts remove test-generated exchange data, but we aren't cleaning up our OneDrive file creation.  Technically, the golang purge script can remove onedrive folders.  But those only get so far as the deletion-recovery folder, and graphapi is unable to remove the file from there, requiring manual intervention from the devs for full cleanup.

## Acceptance Criteria
* Write a pwsh script for deleting test-generated onedrive folders and files.
* Add this script to the `purge-m365-user-data` action.
* Make sure the files get removed from any retention/recovery folders as well.

**Comment by gmatev** [comment]
This is actually done
