### ISSUE TITLE
Optionally reduce new graph connector data enumeration

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1547]
## Issue
Currently, graph connector enumerates either all sites or all users, depending on the data selection.  There are many cases where only a finite (often single) user or site needs to be retrieved.  In these cases, a new graph connector should _optionally_ accept a list of user or site ids, and only retrieve those specified resources.

**Comment by vkamra** [comment]
#1994 is related

**Comment by ashmrtn** [comment]
merged fix to reduce enumeration of users. Unassigning for now as other work has come up

**Comment by gmatev** [comment]
Is this still relevant?

**Comment by ashmrtn** [comment]
still relevant, we should change when enumeration of sites is done. Right now it's done when we create a GraphConnector instance for a SharePoint backup. This could lead to enumerating sites multiple times if multiple sites are being backed up

**Comment by ryanfkeepers** [comment]
closing: work was done within other tickets
