### ISSUE TITLE
Combine blogs and website

### ISSUE THREAD

**Issue by ntolia** [alcionai/corso#1551]
We are going to combine the website and the docs and move everything into the Docusaurus site (under `docs`). The `website` directory should go away after that and so will `docs.corsobackup.io` (CloudFront distribution will be deleted, bucket contents will disappear, etc.).

We will therefore need to update CI to reflect this change. Everything from `docs` should get published to `corsobackup.io` moving forwards and not the docs bucket. 

There also needs to be a way to deploy the new site independent of Corso releases as we will be adding more frequent blog posts.

There is an open issue on how to publish updated blog posts with unreleased docs but we should hopefully be able to handle that with [Docusaurus versioning](https://docusaurus.io/docs/versioning) and [multi-instance](https://docusaurus.io/docs/docs-multi-instance) docs.

**Comment by ntolia** [comment]
Note that for pushes from `main`, we will need to retain the last released version number.

**Comment by meain** [comment]
Currently the publish is done via https://github.com/alcionai/corso/tree/main/.github/workflows and https://github.com/alcionai/corso/blob/docs-push-main-ci/.github/workflows/docs-push.yml . Let me merge them into a new job.

-  [ ] Combine website/docs publish from main
-  [ ] Update CI for docs/website on PR

**Comment by ntolia** [comment]
Feel free to rename the docs directory to website to make it more clear too.

**Comment by meain** [comment]
![2022-11-21-16-49-34](https://user-images.githubusercontent.com/14259816/203037705-1643a3e7-6f68-43bd-b705-27ccf7cdb98b.png)

It does not seem to be having the right colors when the system is in light mode. 
/cc @ntolia

**Comment by ntolia** [comment]
> It does not seem to be having the right colors when the system is in light mode. /cc @ntolia

Yes, light mode should be (temporarily) disabled on main. Is that not working for you? My system default is white and so, I wonder if there is something I am not seeing.

**Comment by meain** [comment]
https://github.com/alcionai/corso/pull/1573 seems  to have fixed it.
