### ISSUE TITLE
SharePoint Libraries Restore

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1615]
## Issue
Implement restore functionality for SharePoint libraries.
- ~Restricted directories~ #2644 
- [x] Backup Details Compliance #1747 
- [x] Fix restore workflow #2489
-  ~e2e tests~ Finish in separate ticket #2525

**Comment by dadams39** [comment]
Required issues for SharePoint.Libraries restore to be completed:
- #1936
- #1938 
- #2064

**Comment by dadams39** [comment]
System Document libraries were excluded on 2/24/2023. 

Separate tracker for the issue: 
- https://github.com/alcionai/corso/issues/2644
