### ISSUE TITLE
Add backup data statistics to Backup model

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#1622]
This tracks adding additional statistics on the backup (logical data, etc.) to the `Backup` model and displaying via `list backups` cmd

**Comment by vkamra** [comment]
@meain - the Kopia snapshot manifest has stats related to the total backup size - we should push this data into the Backup model *or* retrieve this when the backup model is enumerated.

This is what a Kopia snapshot manifest contains for example:
```
$ ./kopia manifest show c794d43ade1de712549d44132633b17b
// id: c794d43ade1de712549d44132633b17b
// length: 815
// modified: 2022-11-04 17:13:44 PDT
// label type:snapshot
// label username:corso
// label exchangecontacts:
// label exchangeemail:
// label exchangeevents:
// label hostname:corso-host
// label path:NGQ2MDMwNjAtMThkNi00NzY0LWI5YmUtNGNiNzk0ZDMyYjY5
{

  "description": "",
  "startTime": "2022-11-05T00:13:01.105603Z",
  "endTime": "2022-11-05T00:13:44.248126Z",
  "stats": {
    "totalSize": 36541799,
    "excludedTotalSize": 0,
    "fileCount": 574,
    "cachedFiles": 0,
    "nonCachedFiles": 574,
    "dirCount": 32,
    "excludedFileCount": 0,
    "excludedDirCount": 0,
    "ignoredErrorCount": 0,
    "errorCount": 0
  },
  "rootEntry": {
    "name": "NGQ2MDMwNjAtMThkNi00NzY0LWI5YmUtNGNiNzk0ZDMyYjY5",
    "type": "d",
    "mode": "0777",
    "mtime": "1754-08-30T22:43:41.128654848Z",
    "obj": "k1159f09730fb8942efe71682eb65bbad",
    "summ": {
      "size": 36541799,
      "files": 574,
      "symlinks": 0,
      "dirs": 32,
      "maxTime": "2022-11-05T00:13:44.247365Z",
      "numFailed": 0
    }
  },
  "tags": {

    "exchangecontacts": "",
    "exchangeemail": "",
    "exchangeevents": ""
  }```

**Comment by meain** [comment]
I think if we can pull this info without explicitly adding to `Backup`, I'll go that route as we can avoid duplicating the data in both places.

**Comment by meain** [comment]
@vkamra Is the idea to expose the the size info via [`BaseModel`](https://github.com/alcionai/corso/blob/467c3c699c4a165b87189347a1c872c718e0def0/src/internal/model/model.go#L41)?

**Comment by ryanfkeepers** [comment]
I don't think we want this attached to the BaseModel, primarily to maintain separation of concerns (a model is not always a backup).  Exposing it through the [Backup](https://github.com/alcionai/corso/blob/467c3c699c4a165b87189347a1c872c718e0def0/src/pkg/backup/backup.go#L17) is direct enough for now.  If we find reason to provide manifest stats in other structures in the future, we can move to a more generic abstraction as needed.

**Comment by meain** [comment]
The backup info provided by kopia is already available in `Backup`. I've added a PR to display the size info when running the `backup list` command [here](https://github.com/alcionai/corso/pull/1648). What all fields should we display when running the list command?

**Comment by ryanfkeepers** [comment]
@meain I forgot to bring this up in the PR: since the tabular output has changed, the `quickstart.md` docs also need an update to sync with the current output.

**Comment by meain** [comment]
@ryanfkeepers The changes to the tabular output was reverted and did not make it to `main`.

**Comment by rajatkateja** [comment]
@meain I think this suffices. Thanks! I will try to use these and get back to you if needed.
