### ISSUE TITLE
GC: OneDrive: Drive Test is flaky.  Refactor Required

### ISSUE THREAD

**Issue by dadams39** [alcionai/corso#1688]
Test located in `src/internal/connector/onedrive/drive_test.go`
Test: `func (suite *OneDriveSuite) TestCreateGetDeleteFolder()` noted to have inconsistent behavior.
Locally, tests will pass; however, the failure that presents when deployed is as follows:
```java
drive_test.go:104: 
          	Error Trace:	/home/runner/work/corso/corso/src/internal/connector/onedrive/drive_test.go:104
          	Error:      	elements differ
          	            	
          	            	extra elements in list A:
          	            	([]interface {}) (len=2) {
          	            	 (string) (len=34) "01ZWH4M4NGSVNLKFOFTJBJZQAZVYAX4AMF",
          	            	 (string) (len=34) "01ZWH4M4JTBZ667W4GGFFJPL4NHFHK7IQI"
          	            	}
          	            	
          	            	
          	            	listA:
          	            	([]string) (len=2) {
          	            	 (string) (len=34) "01ZWH4M4NGSVNLKFOFTJBJZQAZVYAX4AMF",
          	            	 (string) (len=34) "01ZWH4M4JTBZ667W4GGFFJPL4NHFHK7IQI"
          	            	}
          	            	
          	            	
          	            	listB:
          	            	([]string) {
          	            	}
```
This suggests that `GetAllFolders()` function on L91 folders does not contain any folders that match. Tests passes locally for several developers. Need to investigate what part of the CI environment is causing the discrepancy. 

Temporary fix:
- disable test
- Long-term fix: Refactor the test to ensure local and deployed tests have the same outcome.
The 
- See [run](https://github.com/alcionai/corso/actions/runs/3621051818/jobs/6104617378)

**Comment by ashmrtn** [comment]
pulling info here from another PR so it's easy to find:
>the function being tested is used in the purge script. Any issues we see in it, whether the test is enabled or not, may lead to purging more data than we intend when we run the purge script

**Comment by dadams39** [comment]
Test disabled at this time.

**Comment by dadams39** [comment]
Test re-enabled in #1739. 

Debrief
===
- Leading up to the version upgrade within #1479 caused the keys within the `AdditionalData` to change.  Therefore, the `Get()` command only returned the first 10 items which led to an inconsistent return. Changes within #1479 and #1739 resolved the issue.
