### ISSUE TITLE
OneDrive kopia-assisted incrementals deadlock

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#1702]
Backups that use kopia-assisted incrementals deadlock when backing up OneDrive. From inspecting the code, the most likely cause appears to be a mismatch in the expectations of what items will be read between kopia and the observe package. OneDrive currently creates an observe reader (with a WaitGroup counter) for each item, but does not detect if the item will actually be uploaded to kopia. Since kopia may skip unchanged files, this likely leads to a deadlock

[observe package](https://github.com/alcionai/corso/blob/5533ada9beb2b803ea6d0893d00ceb055dccb439/src/internal/observe/observe.go#L205) progress function with `WaitGroup`

OneDrive [code](https://github.com/alcionai/corso/blob/5533ada9beb2b803ea6d0893d00ceb055dccb439/src/internal/connector/onedrive/collection.go#L203) that creates readers with progress bar when before it's known if the item data will be required

Delaying making the progress reader until it's known the item data is required will likely fix the deadlock

**Comment by ashmrtn** [comment]
after testing the above, there's also probably more to the issue than just the observe package. It would probably be more efficient to delay fetching the actual item data until it is known the data is actually needed

**Comment by ashmrtn** [comment]
after more thought, it most likely is an issue with the `WaitGroup` in the observe package. The thing I missed previously though is that even if data is not uploaded to kopia, a `Reader` still [needs to be handed](https://github.com/alcionai/corso/blob/a9d7f0fd27c45c455576b2ab2da7d1392fb0da6e/src/internal/kopia/wrapper.go#L358) to kopia because kopia's `StreamingFile` initializer [requires](https://github.com/kopia/kopia/blob/04fcedad1267f9d9ecfab27fb38c3f9aa1d6308f/fs/virtualfs/virtualfs.go#L196) it. Therefore, `ToReader` is not a good indicator of whether or not data will be uploaded to kopia

**Comment by ryanfkeepers** [comment]
Possible solutions:

### 1 - Kopia Patch
Allow `StreamFile` to passthrough a call to produce an io.reader, here:  https://github.com/kopia/kopia/blob/04fcedad1267f9d9ecfab27fb38c3f9aa1d6308f/fs/virtualfs/virtualfs.go#L178

This would allow deferral of a reader (and thus the streaming of data) until kopia requests it.

### 2 - wrapped reader in Observe

Create a `LazyItemProgress(io.ReadCloser, etc...) => io.readCloser` func in the observe package that wraps `ItemProgress`: https://github.com/alcionai/corso/blob/main/src/internal/observe/observe.go#L205.  Defer the itemProgress call (and thus the bar/wg creation) call until Read is called.

**Comment by vkamra** [comment]
@meain - I recommend we go with option #2 above i.e. wrap `observe.ItemProgress` [here](https://github.com/alcionai/corso/blob/main/src/internal/connector/onedrive/collection.go#L256) in a reader that only initializes that on the first Read

**Comment by vkamra** [comment]
Pushed a PR here https://github.com/alcionai/corso/pull/2126
