### ISSUE TITLE
CLI: progress bars clobber end-of-run output.

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1720]
## Issue
The mpb progressbar package utilizes [cursor position in the shell](https://github.com/vbauerster/mpb/blob/master/cwriter/writer.go) to manipulate line deletion and re-rendering in order to updates its bars.  We already know this overwrites logs written to stdErr.  In the event of a race condition, we've also recently tracked it overwriting end-of-run printouts on stdOut.  (side note, write channel is irrelevant here since, once the line is written, it's able to be erased from the shell via cursor position).

## Solution
- stdOut writes  
end-of-run outputs (tables of backups or items, json dumps, etc) should be buffered up until the progress bar in the `observe` package moves to a completed state.  After this is complete, the printer can Flush all buffered writes.  This may have memory concerns for full-scale backups, alternatively we may also want to consider blocking writes until it is safe to do so.

- stdErr writes and logging  (optional)
logs are already buffered by the zap package.  But we don't want to withhold logging until the end of the run.  An alternative with less friction might be to provide a hidden `--log-file <filepath>` flag that developers can use to [write logs to a file](https://github.com/uber-go/zap/issues/294) instead of the console.  This would allow for simultaneous log gathering and progress bar displays.

**Comment by dadams39** [comment]
Complications
====
- If a failure is encountered during `restore` operation, the resulting failure is overwritten
- If a list of IDs is returned from a backup, one of the IDS will be 

Light Fix
----
- Commands can be suffixed with `--hide-progress` to prevent clobbering of output.

**Comment by ryanfkeepers** [comment]
Closing: fixed with 1990.
