### ISSUE TITLE
Initial download slow when using Quickstart Instruction with Invoke-WebRequest

### ISSUE THREAD

**Issue by Theragus** [alcionai/corso#1746]
Hello,

https://corsobackup.io/docs/quickstart/#download-corso
Using Invoke-WebRequest in PowerShell for downloads is extremely slow when counting the downloaded bytes is not disabled.
See also here  -> https://stackoverflow.com/questions/28682642/powershell-why-is-using-invoke-webrequest-much-slower-than-a-browser-download

To significantly speed up download speed you should consider adding 
```powershell
$ProgressPreference = 'SilentlyContinue'
```

to the quickstart instruction or use something like BITS in PowerShell for downloading files from Repos.

Best regards
Theragus

**Comment by ntolia** [comment]
@Theragus Thank you for the report. Let me verify the command and update the docs.

I did look at BITS earlier but I don't want to introduce additional requirements for downloads.

**Comment by ntolia** [comment]
@Theragus The suggested change has been merged and should now be live. Really appreciate the feedback! 🙏 

Also, apologies for the late response to the issue as I didn't catch it when it was filed.
