### ISSUE TITLE
SharePoint Libraries: missing sharepoint ItemInfo

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1747]
## Issue
Not all items in a sharepoint library backup contain a `SharepointIds` drive value.  This slices out the driveID and webURL from the details.SharePointInfo.  See line: https://github.com/alcionai/corso/blob/main/src/internal/connector/onedrive/item.go#L140

## Acceptance Criteria
- [ ] All SharePointInfo structs must have a populated `Owner` and `WebURL` value.  If discovery is not available (ie: the data isn't present in the driveItemable), backfill these values by passing down the data from the backup creation request.

### Carried forward from 2064
SharePoint's drive permissions can require certain permissions prior to the upload of documents or directories to a protected location. By default, `_catalog` directories do not allow for upload.

Ensure 
Add more metadata to backup to identify restricted directories

**Comment by dadams39** [comment]
Issue takes over concerns reflected in #2064

**Comment by dadams39** [comment]
`SharepointIds` are a regular property for driveItems. When using dataQueries, the options have to include the field in order for it to be populated. For driveItems, we can construct the webURL from additionalData. If it is possible for a SharePoint drive to not possess `sharepointIds.GetId()`, then it should be updated with information from the selector at the end of the call.

**Comment by ryanfkeepers** [comment]
> then it should be updated with information from the selector at the end of the call.

Small preference: I'd rather us pass down the data eagerly than hydrate it lazily.
