### ISSUE TITLE
Emit 'Corso Start' as the CLI starts on any operation

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso#1761]
Goal would be to have an event that allow to determine if users are running into issues. `Corso Start` without a corresponding subsequent event would indicate a problem.

**Comment by vkamra** [comment]
@neha-Gupta1 - Follow up on this after we do #1762. This would involve firing the Corso Start event for each CLI operation.

**Comment by neha-Gupta1** [comment]
Do we want to add this code to 'CLI' package or the `pkg` package? 
Adding it to CLI will provide us events only when actions done from Corso's CLI.

**Comment by neha-Gupta1** [comment]
Completed in https://github.com/alcionai/corso/pull/2534
