### ISSUE TITLE
Bug: graph api retries on a 429 result in an empty payload

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1778]
## Issue
Graph client POST requests that result in 429 will frequently (always?) result in a `400 "EMPTY PAYLOAD"` failure when the request is retried.  By tracking in request middleware we have confirmed that the body is truly reduced to nearly 0 bytes (usually there's ~25 bytes of header data).  It is unknown whether this bug exists within the graph sdk package, or is caused by our usage of it.

## Acceptance Criteria
- [x] Investigate the bug cause.
- [x] Produce reliable reproduction (see branch https://github.com/alcionai/corso/tree/dec1ci for local repro).
- [x] Fix bug / submit ticket to msoft team.

**Comment by meain** [comment]
Looks like I am able to reliably repro this even with the new version. I was also able to repro it separate on a simple folder create, so don't think this is from how we us it. Opened an issue at https://github.com/microsoftgraph/msgraph-sdk-go/issues/341 .

**Comment by meain** [comment]
Fixed via https://github.com/alcionai/corso/pull/1912
