### ISSUE TITLE
Backup fails with `model has no StableID`

### ISSUE THREAD

**Issue by meain** [alcionai/corso#1823]
Every backup after the very fist backup on a new bucket seems to fail with this error:

```
Error: 1 error occurred:
        * Failed to run OneDrive backup for user [J**L@8**0.onmicrosoft.com]: 2 errors occurred:
        * errors prevented the operation from processing
        * connecting to M365: model has no StableID
```

I have not been able to go in depth into the issue, but just from a git bisect, looks like it got added in https://github.com/alcionai/corso/commit/4d46847f6c2d127638c814f6fd28c4fbd0e7e4e6 . You can repro it by deleting all the backups in a bucket and then trying to back it up twice (`./corso backup create onedrive --user $CORSO_M365_TEST_USER_ID`). It will fail on the second backup.

**Comment by vkamra** [comment]
@ryanfkeepers - can you triage?

**Comment by ryanfkeepers** [comment]
I have half of the bug figured out: an incorrect tag key skipped pulling the backup ID from the tags.

There's another half I'm going to need additional eyes on for help.  The model store says the backup doesn't exist.  I can, however, look up the same backup by ID with a `list onedrive --id id` command.  Currently investigating the difference.

**Comment by ryanfkeepers** [comment]
^ Other half fixed up.

**Comment by meain** [comment]
This should now be fixed from #1830

**Comment by meain** [comment]
Seems to now fail with the following error:

```
Error: 1 error occurred:
        * Failed to run OneDrive backup for user [JohannaL@8qzvrj.onmicrosoft.com]: 2 errors occurred:
        * errors prevented the operation from processing
        * connecting to M365: getting backup: getting ModelStoreID: not found
```

**Comment by ryanfkeepers** [comment]
Hmm, that should have been the "second half" of the bug that got fixed.  I"ll look into it.

**Comment by ryanfkeepers** [comment]
@meain I'm unable to repro that error.  Can you provide the list of steps you used?

**Comment by meain** [comment]
I was hitting this error on the very first backup with `144d04756`, but somehow I am not able to repro it now.
