### ISSUE TITLE
Nightly Load Test Failure: Repository Load Test

### ISSUE THREAD

**Issue by dadams39** [alcionai/corso#1824]
Failure within: `/corso/src/pkg/repository/repository_load_test.go:265`
The probable cause is that the mock data used is lacking a field that is now required. 

Error Details
===
```java
Failed to upload RestoreExchangeObject: exchange-events: uploading event during RestoreExchangeEvent:  TimeZoneNotSupportedException A valid TimeZone value must be specified. The following TimeZone value is not supported: ''.
```

Error occurred in the following [run](https://github.com/alcionai/corso/actions/runs/3700968575/jobs/6269944675)

**Comment by gmatev** [comment]
Is this still relevant?
