### ISSUE TITLE
properly handle isRead status changes in Exchange mail

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#1865]
Changes to the `isRead` flag in M365 do not update the mod time of the email. This leads kopia assisted incrementals to skip re-uploading the item because it thinks that nothing has changed. GraphConnector should update the item's information to ensure kopia.Wrapper picks up on the changes (i.e. set the mod time if the item is from a delta or something?)

**Comment by vkamra** [comment]
We will document as known issue and not fix. Can reopen if needed.

**Comment by ashmrtn** [comment]
double checked documentation and it's in the known issues section
