### ISSUE TITLE
Backup is created per data category in exchange

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#1874]
### Issue:

Corso is creating a backup per-<user/service/data category> when `backup create exchange --user <user>` is invoked i.e. a separate backup ID for the email, contacts and calendar.

### Expected:
`backup create exchange --user <user>` creates a single backup

**Comment by vkamra** [comment]
This is related to some of the changes being made to enable incremental backups on by default  (see #1617) where we added <data category> in addition to <service/resource owner> when creating backups.

This was unintentional and should get resolved in the next release to only create a single backup per user.

**Comment by ashmrtn** [comment]
resolved by patch series linked in #1617
