### ISSUE TITLE
add flag to force full backup

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#1901]
Incremental backups increase the chance that Corso gets into a state where it can't complete a successful backup because new backups depend on the success and correctness of backups before them. Furthermore, the fact that Corso is going to default to trying to make an incremental backup makes it such that the user must delete older backups if they want to force a full backup for any reason.

We should provide a smoother and less destructive experience for making a full backup even when the incrementals code is enabled by providing a (possibly hidden) CLI flag that forces a full backup

**Comment by ryanfkeepers** [comment]
Started with the inverse: a flag to _enable_ incremental backups for exchange.  When we release that behavior and standardize incrementals for exchange, we can use this ticket to remove that feature flag and replace it with a forced full-backup operation.

**Comment by ashmrtn** [comment]
Having a flag to disable a full backup may also require a minor change in how kopia.Wrapper works. Currently `BackupCollections` takes a single list of bases to make the incremental off of. These bases are used for both [building the in-memory hierarchy](https://github.com/alcionai/corso/blob/37f1a3eca5aa2eba21352a1a663eee7263583ab2/src/internal/kopia/wrapper.go#L145) to hand to kopia and [giving to kopia](https://github.com/alcionai/corso/blob/37f1a3eca5aa2eba21352a1a663eee7263583ab2/src/internal/kopia/wrapper.go#L150) to find cached files (aka kopia-assisted incrementals).

To disable delta token incrementals, we should skip handing the bases to the function that builds the in-memory hierarchy. However we should still take advantage of kopia-assisted incrementals
