### ISSUE TITLE
track and return errors when updating item details in `kopia/upload.go`

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#1915]
Backup details is populated in part by a callback function that kopia calls when uploading items. However, the [callback](https://github.com/alcionai/corso/blob/741b36da98b391a962a2331bf7dc37736f0c9241/src/internal/kopia/upload.go#L135) does not allow returning errors or logging errors with our logger embedded in the context

We should expand the existing `corsoProgress` struct to track errors internally and return them after the snapshot has been completed. Errors that progress tracks will represent items that we could not gather details for. Not reporting these errors means backups may have inaccessible items in them

**Comment by vkamra** [comment]
At minimum - log these errors
