### ISSUE TITLE
GC: Restore: SharePoint: Libraries: Restricted directories

### ISSUE THREAD

**Issue by dadams39** [alcionai/corso#1938]
- Enable the restoration of System Document Libraries for `SharePoint.Libraries`.

`Site Pages` are not included in this feature
#2524 required prior to implementation

**Comment by dadams39** [comment]
Restricted directories are found in drives with URLs that have paths that contain `_catalogs`. These require SharePoint API(s) or soon-to-be-released calls from Microsoft Graph Beta API to be able to place data within these directories. 
The completion of the restore function for restricted libraries involves 3 phases:
- Phase 1
  - Add more metadata to identify these directories.
- Phase 2
   - Disallow the uploading of content to these drives. At this point, restore for `SharePoint.Libraries` can be enabled.
- Phase 3
  - Enable the uploading of content via a different workflow for restricted files.

**Comment by dadams39** [comment]
Recent updates to Microsoft Graph for SharePoint no longer bring in System drive libraries.

**Comment by dadams39** [comment]
- The effort regarding `OneDrive` permissions may not necessarily solve this issue. System libraries such as `Form Templates` and `Style Libraries` have the same permissions. However, `Form Templates` allows upload, and  `Style Libraries` does not.

**Comment by gmatev** [comment]
Will be done as part of https://github.com/alcionai/corso-roadmap/issues/37
