### ISSUE TITLE
GC: Backup: OneDrive: DriveItem M365 Object encapsulation not used  when retrieving data

### ISSUE THREAD

**Issue by dadams39** [alcionai/corso#1939]
OneDrive objects are stored as bytes within the Corso back store. This means that certain fields such as 
`cTag` or `eTag` are not accessible for the file.

**Comment by vkamra** [comment]
@dadams39 - we will have a placeholder for metadata for DriveItems with the work @meain is doing for persisting permission metadata. Let's look into that.

Removing tech-debt label - let's track this as part of feature work where it's needed.
