### ISSUE TITLE
GC: Backup: OneDrive: Drives M365 Object encapsulation not used when retrieving data

### ISSUE THREAD

**Issue by dadams39** [alcionai/corso#1942]
At this time, `Drive` folders are not saved within Corso. Therefore, certain information such as whether or not the drive is `Shared` is not saved. This information changes how items within these types of directories can/should be restored.

**Comment by vkamra** [comment]
@dadams39 - we will have a placeholder for metadata for DriveItems with the work @meain is doing for persisting permission metadata. Let's look into that.

Removing tech-debt label - let's track this as part of feature work where it's needed.
