### ISSUE TITLE
Refactor statistic aggregation in BackupOp

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#1947]
BackupOp current determines how many resource owners participated in a single backup. However, we're moving to a model where BackupOp (and hence backups the user can see) are 1:1 with resource owners. This provides an opportunity to simplify the code we use for aggregation

**Comment by vkamra** [comment]
Scrubbing backlog. Closing some of the older items that haven't been prioritized - will let them resurface if there is pain.
