### ISSUE TITLE
Refactor GraphConnector status aggregation

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#1951]
GraphConnector currently assumes that all collections it returns need to report a status to it. This means that all collections created in it need to take and manage a `StatusUpdater` parameter and call it at the right time (there may be race conditions between calling the status updater and when GraphConnector initializes the WaitGroup it uses to track collection completion)

Going forward, it may be less error-prone to design and implement another way to gather statistics from the collections

**Comment by vkamra** [comment]
Scrubbing backlog. Closing some of the older items that haven't been prioritized - will let them resurface if there is pain.
