### ISSUE TITLE
Enable incremental backups

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#1955]
This tracks enabling the incremental backup feature (currently for Exchange only) by default.

This feature is currently behind a feature flag (`--exchange-incrementals`) in the backup command. 

- [ ] https://github.com/alcionai/corso/issues/1956

**Comment by gmatev** [comment]
I have reviewed our existing documentation and I'm nog sure there is anything more to document here. The concepts section already covers incremental backups and the commands are self-documenting.

**Comment by gmatev** [comment]
@ryanfkeepers @vkamra I propose we close this

**Comment by ryanfkeepers** [comment]
closing
