### ISSUE TITLE
Move sharepoint site retrieval to connector/discovery

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1995]
## Issue
The retrieval of users was moved from graph_connector to discovery to aid in exposing apis for sdk consumers.  Sharepoint sites (which are a category of resourceOwners similar to users) were being added to the graph_connector file around the same time, thus missing that migration.  It makes the most sense to co-locate both types of resource owners in the discovery package.

**Comment by gmatev** [comment]
This probably needs to happen sooner rather than later since the site discovery is being consumed.
