### ISSUE TITLE
Incrementals - Calendar Event Delta Handling

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#2022]
## Issue
Delta coverage for calendar events is incomplete.

### Events vs Views
The [Calendar Event](https://learn.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&tabs=http) object stored by Corso does not support delta queries.  There is an alternative event object, the [Calendar View](https://learn.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http), which is (quoting the docs) "a set of [event](https://learn.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0) resources that have been added, deleted, or updated in a calendarView (a range of events defined by start and end dates)".  It's possible that Corso should store both types.

### Lazy Event Pulling
Since the primary event set does not have delta support, we may have to find alternative ways to minimize data retrieval.  One option is a lazy pull: only perform the full item download if the item's modTime has changed between kopia and GC.

**Comment by ashmrtn** [comment]
this is related to
* #2023
