### ISSUE TITLE
Fine-grained supply of delta incrementals

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#2068]
## Issue
Kopia wrapper currently accepts a single list of manifests to use as incremental bases for both kopia-assisted and delta behavior.  However, under certain conditions (missing backup IDs or backup details), one or more of the assist-capable bases are not usable for delta bases.

Causes for delta unusability:
* The backup ID is missing, or references missing storage.
* The backup details ID is missing, or references missing storage.

## Acceptance Criteria
* Notify Kopia wrapper of the difference in usability between the manifest bases.  This can be done by passing two separate slices (one for assists, one for deltas), or by augmenting the items in the slice with additional metadata.

**Comment by ashmrtn** [comment]
closing this as kopia wrapper now takes a set of bases that differentiates between merge bases and assist bases
