### ISSUE TITLE
CLI Progress shows user lazily.

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#2075]
## Issue
When making a backup, the user in question isn't displayed in a progress bar until items are queried by graph.  Ex:
```sh
Connecting to repository:     13s done
Connecting to M365:      1s done
Discovering items to backup:     21s done
∙ contacts - foo@bar.microsoft.com:      2s done
∙ email - foo@bar.microsoft.com:     10s done
∙ events - foo@bar.microsoft.com:      7s done
```

This design made sense when backups could contain multiple resource owners.  Now that backups have a single-owner constraint, this information is both repetitious and lazily displayed.  A more effective display would be a prior header like, "Backing up foo@bar.microsoft.com".

**Comment by meain** [comment]
Closing this, we now show user at the start of a backup.
