### ISSUE TITLE
handle delta token expiration

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#2124]
A delta token expiring should result in ignoring any other metadata from the previous backup as all items will need to be enumerated again and a fresh delta token persisted at the end of the enumeration

**Comment by ashmrtn** [comment]
Just thought of another thing that needs to be handled for this. We need to explicitly find and notify kopia of deleted folders. Since the full folder map will be constructed (we have to start from scratch again) this should be just comparing the old folder map to the new one and marking entries not in the old one as deleted. All the collections in the new map should be marked with DoNotMerge

**Comment by meain** [comment]
@ashmrtn On your [previous comment](https://github.com/alcionai/corso/issues/2124#issuecomment-1411089847), does it matter what the `DoNotMerge` state is on deleted items?

**Comment by ashmrtn** [comment]
>does it matter what the DoNotMerge state is on deleted items?

no, the flag is not checked if the folder was deleted so it's fine

>this is for kopia incrementals and not strictly "delta incrementals" if I am not mistaken.

DoNotMerge is for delta token-based incrementals, but it's used to communicate extra information to kopia wrapper. Essentially it allows selectively skipping merging for the directories that have it set
