### ISSUE TITLE
Improve "licensed user" check for M365 services

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#2145]
We [currently](https://github.com/alcionai/corso/blob/main/src/internal/connector/onedrive/drive.go#L395) check whether a user has a OneDrive drive by looking at what M365 SKUs the user has a license for.

The check uses a version of this list that we've added to the repo. The check seems brittle and the approach may not scale.

Alternatively - maybe an approach where we query existence of a drive or mailbox might be sufficient.

**Comment by vkamra** [comment]
Adding to current cycle because we do need add a check for Exchange (currently missing)

**Comment by vkamra** [comment]
Exchange fixed with #2156. Need to address OneDrive going forward.

**Comment by meain** [comment]
@vkamra wouldn't https://github.com/alcionai/corso/pull/2161 handle the case for OneDrive? Should we close the issue?
