### ISSUE TITLE
Emails with embedded images are not being restored correctly

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#2163]
Emails with embedded images are being restored with broken links.

Repro steps:
1) Create an email with an embedded image (In outlook - send an email to the user with an image pasted)
2) Restore -> Email restores correctly but image has a broken link

**Comment by vkamra** [comment]
Ok - looks like this is related to the behavior of `hasAttachments` when the message has inline attachments

From https://learn.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0#properties : 
```Indicates whether the message has attachments. This property doesn't include inline attachments, so if a message contains only inline attachments, this property is false. To verify the existence of inline attachments, parse the body property to look for a src attribute, such as <IMG src="cid:image001.jpg@01D26CD8.6C05F070">.```

**Comment by vkamra** [comment]
@dadams39 - can you pick this one up please? The recommendation in the link is to parse the body to see if there's a `src` attribute.

**Comment by dadams39** [comment]
## Background
Related to https://github.com/alcionai/corso/issues/978
This is similar to the problem experienced where `OneDrive` attachment would not restore. Exchange API update turned these into links which are correctly parsed with HTML. 

Approach
=====
Verify the difference between the current restored link and `OneDrive` enabled-links.
