### ISSUE TITLE
OneDrive does not use kopia assisted incrementals

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#2267]
## issue
The onedrive lazy reader only wraps the item transmission, not its download.  This means that even in the case where kopia-assisted incrementals could be used, they still incur the majority of the effort in the transaction.

## Acceptance Criteria
Migrate the http download of the item into the lazy reader so that kopia assistance is maximized on older file backups.

**Comment by vkamra** [comment]
Fixed
