### ISSUE TITLE
Fix CI build downloads and related docs

### ISSUE THREAD

**Issue by ntolia** [alcionai/corso#2278]
I expected to follow the [docs](https://corsobackup.io/docs/developers/build/) to get to an unreleased build with the fix I wanted. However, I ran into a few issues:

- Confusing docs. The docs say:
   ```
   You can download binary artifacts of the latest commit from GitHub by navigating to
   the "Summary" page of the Build/Release Corso CI job that was run for that commit.
   You will find the artifacts at the bottom of the page.
   ```

   However, this leads folks in the wrong direction but the CI job summary page for the actual PR only has website binaries. See [this](https://github.com/alcionai/corso/actions/runs/4013465228) as an example for PR #2275. The only place I could find the binaries were in the build on `main` [here](https://github.com/alcionai/corso/actions/runs/4013612502#artifacts). We should either clean up the docs or make sure the binaries are available from the PR CI summary.

- Suboptimal binary packaging: We shouldn't compress Linux and macOS artifacts using `zip` but instead use `tar.gz`.

**Comment by meain** [comment]
> https://github.com/alcionai/corso/pull/2275. The only place I could find the binaries were in the build on main [here](https://github.com/alcionai/corso/actions/runs/4013612502#artifacts).

The artifacts are only available for commits on main as we don't do all the builds for PRs, let me think of a better way to convey this in the docs.

> We shouldn't compress Linux and macOS artifacts using zip but instead use tar.gz

This is not something we can handle, it is GitHub compressing it on the fly when the user downloads. In fact we are upload the entire  file without compression. Even if we were to upload a compressed file, GitHub wraps it in a zip file when the user tries to download.

**Comment by ntolia** [comment]
Fair enough. Let's just tweak the docs and close this out.
