### ISSUE TITLE
Corso logging improvements

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso#2329]
The following are a number of improvements that we should make to Corso logging to improve supportability and troubleshooring for real world users:
- [ ] ~Log file names currently use UTC - switch to local time for easier identification of the right log. Time stamps inside logs are already in local time~
- [ ] Time stamps inside logs should be in UTC
- [x]  Print out log file name being used with the CLI output. Allows a user who is invoking using CLI to correlate which log file has more details
- [x]  Log Corso version at the beginning of logs
- [x]  Include the command being executed (with appropriate masking of PII like emails addresses and folder names) at the beginning of the log
- [x]  Include final success or failure of command to make the result obvious in the log
- [x]  ~Number of items discovered / backed up is not PII and should not be masked~
- [x]  Long running operations should include INFO logs as they make progress, for example every 1000 items processed
- [x]  Logs should also capture relevant stdout/stderr information that Corso will otherwise output as errors

**Comment by ryanfkeepers** [comment]
> Log file names currently use UTC - switch to local time for easier identification of the right log. Time stamps inside logs are already in local time

Clarifying, the request here is to use local time for the file name, right?

**Comment by ntolia** [comment]
@gmatev @ryanfkeepers Best practices recommend always recording all times in UTC. It becomes a big mess otherwise when we start combining logs from different places in the future (e.g., logs from Corso and AWS). Based on previous experiences, I highly recommend we standardize everything to UTC instead of local time zone.

**Comment by dadams39** [comment]
Suggestion is to clarify retry failure(s):
```bash
2023-01-30T08:52:08.367Z        INFO    graph/service.go:293    graph api error {"status": "500 Internal Server Error", "method": "GET", "url": https://graph.microsoft.com/v1.0/users/user%40errors.net/messages/<messageID>/attachments}
```
In this particular case, this is a failure which looks very similar to an API Timeout and which is retried. Users should be easily able to distinguish between the system resending information and the system exiting after x retries.

**Comment by ryanfkeepers** [comment]
> I highly recommend we standardize everything to UTC instead of local time zone

Yep, I was going to push similarly.  There's also some [side documentation in the repo](https://github.com/alcionai/corso/blob/main/design/time_standards.md) affirming that expectation.  Glad we're agreed about it.

**Comment by ntolia** [comment]
> Users should be easily able to distinguish between the system resending information and the system exiting after x retries.

Good point @dadams39. I've seen when incorrectly-identified logs associated with retries or innocuous failures have led to concerned customers and bug reports.

**Comment by gmatev** [comment]
> @gmatev @ryanfkeepers Best practices recommend always recording all times in UTC. It becomes a big mess otherwise when we start combining logs from different places in the future (e.g., logs from Corso and AWS). Based on previous experiences, I highly recommend we standardize everything to UTC instead of local time zone.

The initial suggestion for local time for the file name was to make it simpler for an end user to identify the right log file - we have one file per command. With the UTC times, it was just not simple to eyeball the logs directory and have an idea of which file you may want based on your recollection of when something has happened. I struggled mightily with this in my testing (was trying to find the log that would correspond to a command I did 30 mins ago)

For timestamps inside the logs, UTC is better. 

I don't feel as strongly here if others feel that identifying the right log is not as much of a problem. Maybe also better when we add info to identify the command in the logs.

**Comment by ryanfkeepers** [comment]
> Maybe also better when we add info to identify the command in the logs.

Speaking of, the PR is out for that addition: https://github.com/alcionai/corso/pull/2331

**Comment by ntolia** [comment]
@ryanfkeepers I converted the issue into a tasklist and marked off the items I belive #2331 addressed. Please do confirm.

@gmatev I agree with the issue in finding log files corresponding to the failed backup. I like your suggestion of printing out the log file which will make it easy to connect things and for us to ask for the right log. I also did add a task to ensure that we log all messages in UTC.

**Comment by ryanfkeepers** [comment]
@ntolia Thanks for the conversion.  Yes, those are correct.

**Comment by ryanfkeepers** [comment]
>  Number of items discovered / backed up is not PII and should not be masked

@gmatev I don't see any location where we're doing this.  Can you provide an example log for me to track down?

**Comment by vkamra** [comment]
> @gmatev I don't see any location where we're doing this. Can you provide an example log for me to track down?

@ryanfkeepers - this seems to be happening correctly during the collection population stage e.g. below.
```
2023-01-31T15:06:19.993-0800	INFO	observe/observe.go:441	done - Collecting Directory	{"user": "***", "category": "events", "dir": "***", "count": 154}
2023-01-31T15:06:40.554-0800	INFO	observe/observe.go:379	Collecting Directory	{"user": "***", "category": "email", "dir": "***"}
2023-01-31T15:06:40.554-0800	INFO	observe/observe.go:379	Collecting Directory	{"user": "***", "category": "email", "dir": "***"}
2023-01-31T15:06:40.692-0800	INFO	observe/observe.go:441	done - Collecting Directory	{"user": "***", "category": "email", "dir": "***", "count": 23}
2023-01-31T15:06:41.143-0800	INFO	observe/observe.go:441	done - Collecting Directory	{"user": "***", "category": "email", "dir": "***", "count": 16}
2023-01-31T15:07:00.343-0800	INFO	observe/observe.go:441	done - Collecting Directory	{"user": "***", "category": "email", "dir": "***", "count": 173}```

I think what might be interesting is to see if we can log this information during delta enumeration (this would be new functionality)

**Comment by ryanfkeepers** [comment]
> interesting is to see if we can log this information during delta enumeration
as part of this ticket, or a follow-up?

**Comment by vkamra** [comment]
> @ryanfkeepers - this seems to be happening correctly during the collection population stage e.g. below.

So an issue discovered is that if the user specified `--hide-progress`, then `observe.CollectionProgress` does not log the count (only the message)

**Comment by vkamra** [comment]
> as part of this ticket, or a follow-up?

This would be part of getting more progress logging in the log file.

**Comment by ryanfkeepers** [comment]
> So an issue discovered is that if the user specified --hide-progress, then observe.CollectionProgress does not log the count (only the message)

Ah, makes sense.  This is logged on closing.  I can look at a quick refactor here.  A better refactor will be to supply the count at the beginning (I wrote this with the assumption that we might not know the count prior to starting the display, and I don't think that holds true).

**Comment by vkamra** [comment]
> Someone ticked this as complete. Is that true? I see timestamps with time zone offsets in the logs above.
I did - reverted that.

**Comment by vkamra** [comment]
Going to close this one - all changes are in other than logging in UTC. Let's stick with what we have there for now and see what feedback we get.
