### ISSUE TITLE
store logical item paths in backup details

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#2412]
Backup details has been leveraging the reporef of an item to serve as the "logical location" of the item in an external service. For example, for an email that resides in folder `Inbox/foo`, the reporef would contain `Inbox/foo` and this would be used to match selectors

This creates a dependency between what is shown to the users/may be consumed by SDK users and how the data is stored in kopia. Adding a separate field representing the "logical location" of an item would be preferable as it decouples the storage layout from other things

**Comment by ryanfkeepers** [comment]
Completed in https://github.com/alcionai/corso/issues/2423
