### ISSUE TITLE
[Bug]: Restore of restored events crashes operation.

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#2490]
### What happened?

Reproduction:
1. Backup exchange events.
2. Restore one or more backed up events.
3. Run another backup, include the calendar created by previous restore.
4. Restore both the originally restored event, as well as the events in the restore calendar.

error:
```
failed to upload RestoreExchangeObject: exchange-events: uploading event during RestoreExchangeEvent:  ErrorDuplicateTransactionId Your request can't be completed. The TransactionId specified in the request has already been used to create a different event.: error status code received from the API
```

Per graph api docs on event resources: https://learn.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0

```
[transactionID is a] custom identifier specified by a client app for the server to avoid redundant POST operations in case of client retries to create the same event.
```

### Corso Version?

main branch

### Where are you running Corso?

macOS 13.2.1, s3

### Relevant log output

```shell
n/a
```

**Comment by dadams39** [comment]
Events have a field called `TransactionID`. It is defined by Microsoft as:
```
[TransactionID is] A custom identifier specified by 
a client app for the server to avoid redundant POST operations
in case of client retries to create the same event.
```

In the case of the repro, the client is explicitly trying to restore a duplicate item.  PR #2611 addresses this by removing certain fields, including `TransactionID`, from the restored event. 

The alternative is to log an info message stating that the event already exists within the storage location.
