### ISSUE TITLE
store directory metadata in directory not parent

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#2532]
If directory metadata continues to be stored in the parent directory then we can't delete it because we can't assume directory names are unique. This metadata would need to be deleted from the parent if the directory was moved, renamed (keyed by folder name), or deleted

There are two ways to solve this:
* store directory metadata in the directory itself and use Fetch() interface on collection during recovery
* use folder IDs for at least the metadata file name (and maybe the directory name to keep things easy to manage)

Implementing the latter is harder so moving the metadata files is preferable

**Comment by ashmrtn** [comment]
can also be seen as part of #2447

**Comment by meain** [comment]
> Implementing the latter is harder so moving the metadata files is preferable

I guess it makes sense to move the metadata to within the folder as we have `Fetch()` and don't have to rely on the ordering. We could probably drop the need to  have a separate name for directory metadata (`.dirmeta`) and just have `.meta` file. The file would be a `.meta` file without any folder name prefix so as to avoid any collision with other meta files for items within the folder.

**Comment by ashmrtn** [comment]
hmmm it is tempting to consolidate the `.meta` and `.dirmeta` suffixes. The paranoid part of me kind of wants to keep them separate though in case we somehow end up with a bug in the code that causes files to have empty meta names. At least then we would have some way to tell them apart?

I don't think it would really matter too much either way so I can update the PR as needed

**Comment by meain** [comment]
Makes sense, lets keep `.dirmeta`. There is no reason no major advantage it changing it to `.meta` anyways.
