### ISSUE TITLE
Sharepoint document libraries support: CLI fit & finish feedback

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso#2786]
## corso backup create sharepoint
- [x] Usage is incorrect and should emphasize using web urls to specify the site 
   * `corso backup create sharepoint  --site <site url> | '*' [flags]`
- [x] Fix examples to use URL 
- [x] Remove `--web-url` flag - use dual `site ulr` or `site ID` similar to how this works for users
- [x] `--data` flag should be hidden default to `files` until `pages` and/or `lists` are introduced 
- [x] Remove Pre-release warning
- [x] Progress output 
   * For each library - `* library - <name of library>`. For example, `* library - Documents`
   * `Queuing items` entries should prefix with name of library - e.g. `Queuing items   /Documents 3/3` - more consistent with OneDrive 

## corso backup details sharepoint
- [x] Remove pre-release warning
- [x] Fix examples using `--site` with a UTR
- [x] Fix flags - model after OneDrive. Specifically fix ordering. Hide unsupported flags (e.g. pages)
```
Flags:
      --backup string                 ID of the backup to explore. (required)
      --site string              Select backup details by site url; accepts '*' to select all sites.
      --library string               Select backup details by Library name; defaults to '*'
      --folder                      Select backup details by folder
      --file                          Select backup details by file name or ID.      
      --file-created-after string     Select backup details for files created after this datetime.
      --file-created-before string    Select backup details for files created before this datetime.
      --file-modified-after string    Select backup details for files modified after this datetime.
      --file-modified-before string   Select backup details for files modified before this datetime.
  -h, --help                          help for sharepoint
```

#### Actual display 
- [x] Remove WebURL - repetitive and not useful since backups are one site at a time 
- [x] Rename Drive => Library
- [x] Parity with OneDrive (except for the Library field)

## corso backup details sharepoint
- [x] Remove pre-release warning
- [x] Fix examples - `--site` usage with WebURL. Make example of names more relatable (use the ones from OneDrive)
- [x] Add example with `--library` - use `Documents`
- [x] Fix flags to support the same selectors as `backup details`
- [x] Fix order to match the order for `backup details`
- [x] Fix usage text for flags to be consistent with working from OneDrive
- [x] Hide unsupported flags

**Comment by ryanfkeepers** [comment]
> Remove --web-url flag - use dual site ulr or site ID similar to how this works for users

@gmatev one hitch with the dual approach: since site IDs contain commas by nature, we can't use comma-delimited inputs there.  ie, we couldn't use `--site foo.com,bar.com`, and could only allow `--site foo.com --site bar.com`.  Unless we want to get into the game of telling users to escape the correct commas and have us split up those values within the command handler, which is a lot.  (side note: this is a topic we still need to address for any display name that allows commas, including onedrive file names)

Alternative proposal:
* Rename `--web-url` to `--site`. 
* Rename the current `--site` to `--site-id`.
* Since we don't expect end users to use site-id normally, we can probably keep `--site-id` hidden.

**Comment by ryanfkeepers** [comment]
> For each library - * library - <name of library>. For example, * library - Documents
Queuing items entries should prefix with name of library - e.g. Queuing items   /Documents 3/3 - more consistent with OneDrive

Do we want both the library as a separate bucket, and the folder as well?  Or is putting the library in the folder sufficient?  Ex:

```
Backing up data:      1s done
Queuing items /Rhine/ 3/3
Queuing items /Rhine/Corso_Restore_10-Mar-2023_23-08-06 3/3
Queuing items /Documents/ 5/5
Queuing items /Documents/Applied 2/2
Queuing items /Documents/Corso_Restore_10-Mar-2023_23-08-06 5/5
Queuing items /Documents/Corso_Restore_10-Mar-2023_23-08-06/Applied 2/2
```

Also, thoughts on putting the count in front of the folder?  Ex:
```
Queuing items 2/2 /Documents/Applied
Queuing items 5/5 /Documents/Corso_Restore_10-Mar-2023_23-08-06 
Queuing items 2/2 /Documents/Corso_Restore_10-Mar-2023_23-08-06/Applied
```

**Comment by gmatev** [comment]
> > Remove --web-url flag - use dual site ulr or site ID similar to how this works for users
> 
> @gmatev one hitch with the dual approach: since site IDs contain commas by nature, we can't use comma-delimited inputs there. ie, we couldn't use `--site foo.com,bar.com`, and could only allow `--site foo.com --site bar.com`. Unless we want to get into the game of telling users to escape the correct commas and have us split up those values within the command handler, which is a lot. (side note: this is a topic we still need to address for any display name that allows commas, including onedrive file names)
> 
> Alternative proposal:
> 
> * Rename `--web-url` to `--site`.
> * Rename the current `--site` to `--site-id`.
> * Since we don't expect end users to use site-id normally, we can probably keep `--site-id` hidden.

@ryanfkeepers in this proposal, `--site-id` only supports a singleId, correct?

For the original requirement, wouldn't something like `\,` when the comma is part of the item as in the case of and actual ID work properly or the shell will automatically remove these by the time it gets to command processing? 

I can be ok with `site-id` if there is no other option

**Comment by gmatev** [comment]
> > For each library - * library - . For example, * library - Documents
> > Queuing items entries should prefix with name of library - e.g. Queuing items   /Documents 3/3 - more consistent with OneDrive
> 
> Do we want both the library as a separate bucket, and the folder as well? Or is putting the library in the folder sufficient? Ex:
> 
> ```
> Backing up data:      1s done
> Queuing items /Rhine/ 3/3
> Queuing items /Rhine/Corso_Restore_10-Mar-2023_23-08-06 3/3
> Queuing items /Documents/ 5/5
> Queuing items /Documents/Applied 2/2
> Queuing items /Documents/Corso_Restore_10-Mar-2023_23-08-06 5/5
> Queuing items /Documents/Corso_Restore_10-Mar-2023_23-08-06/Applied 2/2
> ```
> 
> Also, thoughts on putting the count in front of the folder? Ex:
> 
> ```
> Queuing items 2/2 /Documents/Applied
> Queuing items 5/5 /Documents/Corso_Restore_10-Mar-2023_23-08-06 
> Queuing items 2/2 /Documents/Corso_Restore_10-Mar-2023_23-08-06/Applied
> ```

I'd say the option that is most consistent with onedrive. I believe that is just including it in the path.

**Comment by ryanfkeepers** [comment]
> in this proposal, --site-id only supports a singleId, correct?

One per flag declaration.  So `--site-id cat-uuid,id-uuid --site-id cat-uuid,id-uuid2` still works as a multiple-selection declaration.

> For the original requirement, wouldn't something like \, when the comma is part of the item as in the case of and actual ID work properly or the shell will automatically remove these by the time it gets to command processing?

It's a good question.  I tried to make this work a ways back.  Basically, our flag parsing library (cobra, pflags) doesn't make any attempt to recognize escaped characters.  The user can put in `\\,` if they want, but we'll just get the string `\,`, and nothing else will have changed.  So we, within corso, could make that split.  But the cli library won't do it for us.

> I'd say the option that is most consistent with onedrive. I believe that is just including it in the path.

Onedrive doesn't report the drive name (which is, itself, `OneDrive`) at all.  So this is a unique condition.

I'm okay with keeping it in the path if you are.

**Comment by gmatev** [comment]
> Onedrive doesn't report the drive name (which is, itself, OneDrive) at all. So this is a unique condition.

> I'm okay with keeping it in the path if you are.

I mean keep it in a format consistent with OneDrive. The library is just an organizational artifact. No need to expose it in the output here.

**Comment by gmatev** [comment]
> It's a good question. I tried to make this work a ways back. Basically, our flag parsing library (cobra, pflags) doesn't make any attempt to recognize escaped characters. The user can put in \\, if they want, but we'll just get the string \,, and nothing else will have changed. So we, within corso, could make that split. But the cli library won't do it for us.

You would only escape for the commas that are part of the ID. Cobra should still split things that are not escaped. Or are you saying that the SiteID value is split internally in Corso? If so, is that necessary? As far as I know the ID is always treated at least by graph as a single string. 

Eg. `hostname1\,sitegrouid1\,siteid1,hostname2\,sitegrouid2\,siteid2`

Anyway, i don't expect usage of ids to be common so we can use a separate flag `--site-id`  although it will be a bit inconsistent with other commands, but can probably live with it for now

**Comment by ryanfkeepers** [comment]
> Cobra should still split things that are not escaped.

Cobra has two flag arg parsing modes: `Array` and `Slice`.

Array makes no attempt to split the values. ie:
* --arr a,b => "a,b"
* --arr a,b --arr c => "a,b", "c"

Slice splits every comma, even if the input is "escaped".  ie:
* --slc a,b => "a", "b"
* --slc a,b --arr c => "a", "b", "c"
* --slc a\,b --arr c => "a\", "b", "c"

I ran a quick test on this for proof, and got the resulting output.
```
--arr a\\,b\\,c,d\\,e\\,f --arr aa\\,bb\\,cc,dd\\,ee\\,ff --slc a\\,b\\,c,d\\,e\\,f --slc aa\\,bb\\,cc,dd\\,ee\\,ff \
	
-----
Array ["a\,b\,c,d\,e\,f", "aa\,bb\,cc,dd\,ee\,ff"]
Slice ["a\", "b\", "c", "d\", "e\", "f", "aa\", "bb\", "cc", "dd\", "ee\", "ff"]
-----
```
