### ISSUE TITLE
Metadata files are not counted in backups

### ISSUE THREAD

**Issue by meain** [alcionai/corso#2790]
https://github.com/alcionai/corso/blob/1cbd2e9cfb85e9a363b9d934c0e7ebd16014f89f/src/internal/operations/backup_integration_test.go#L1254

As of now, we only count data files read and not when meta files for items are "read". We should ideally have more fine grained counts for items and meta items. This should also improve the tests around this.

https://github.com/alcionai/corso/pull/2770#issuecomment-1466602963

**Comment by meain** [comment]
@ryanfkeepers @ashmrtn Any thoughts on how/where we should expose this information? Previously brought up [here](https://github.com/alcionai/corso/pull/2770#issuecomment-1466602963). This could also be used to improve the e2e test for permissions delta updates.

**Comment by ryanfkeepers** [comment]
closing: the count bus (https://github.com/alcionai/corso/blob/main/src/pkg/count/count.go) is being used to fulfill this need.
