### ISSUE TITLE
Backup Calendar event instance exceptions

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#2835]
## Issue
Corso correctly backs up the core recurring events, but does not back up individual instances from the recurring event.  This is normally okay, if the recurring event instance is unchanged.  But in the case of changes to a certain instance of the event, those exceptions get sliced out.

## Proposal
Recurring event instance exceptions can be looked up one of two ways.  The first is by querying for exceptions to a recurring event directly.  This is the most direct solution, and cleanly correlates these exceptions to the central event.

https://learn.microsoft.com/en-us/graph/api/event-list-instances?view=graph-rest-1.0&tabs=http
```
https://graph.microsoft.com/{{version}}/users/{{OwnerId}}/events/{{ItemId}}/instances?startdatetime={{StartDate}}&enddatetime={{EndDate}}&$filter=type ne 'occurrence'
```

The second is by running a delta on the calendar view.  This is only available through the beta api, and produces a messier result that cannot be filtered to only exceptions.

https://learn.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-beta&tabs=http
```
https://graph.microsoft.com/beta/users/{{OwnerId}}/calendars/{{ContainerId}}/calendarview/delta?startdatetime={{StartDate}}&enddatetime={{EndDate}}
```

## Deleted instances
According to forum posts, only the calendarView delta is able to display deleted instances.  I have so far been unable to find entries for deleted items.  In both requests, the deleted item is simply absent.

---

TODOS:

- [x] Handle cancelled events
- [x] Handle moved/modified events
- [x] Backup modified attachments
- [x] Restore modified attachments

**Comment by ashmrtn** [comment]
if I understand this right, both of these require using something akin to a calendarView so we'll be bounded by whatever end time we pick right?

**Comment by ryanfkeepers** [comment]
Correct

**Comment by meain** [comment]
Here is what I am planning. We can go with using `events/{{ItemId}}/instances` as that can easily filter out by events and for exceptions, plus has a cleaner output compared to the other option. We can use the start and end time available on the recurring event as the start and end time for our search and for events without an end time, we can just set a default limit (eg: 50 years). As we are filtering by exceptions, this should be a relatively small list.

One possible optimized bit is that we might have to download the exceptions even when none have changed in case we have a change in the original event.

**Comment by meain** [comment]
We do not seem to get deleted items if we filter by `exceptions`. For that, it looks like we have to get the full set of items and figure out which all items don't seem to be present.

According to [this SO thread](https://stackoverflow.com/a/56799190), events cannot be moved to date beyond the next event which might help us limit the search for deleted events, but even still it can be a bit messy.

PS: Also found out that we can also search in a 5 year window [ref](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/events-should-return-all-exceptions-to-recurring-events-instead/idi-p/3601013).

**Comment by meain** [comment]
Although the upstream issue has been closed, the actual change needs more time to land in the SDK(~1 week). Deferring till the change is available.
