### ISSUE TITLE
Compression not being set for streaming files

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#2850]
Kopia [streaming file uploader](https://github.com/kopia/kopia/blob/90b606f5e51cfcd38e8951e983df3dddaee62ea6/snapshot/snapshotfs/upload.go#L339) is not setting the compressor. This needs to be addressed in Kopia and pulled into Corso.

**Comment by ntolia** [comment]
Upstream PR: https://github.com/kopia/kopia/pull/2835
