### ISSUE TITLE
Handle 503 when backing up [large] SharePoint files

### ISSUE THREAD

**Issue by meain** [alcionai/corso#2876]
Large OneDrive backups sometimes end up with a few 503. It might be a good idea to bump up the retries(unless there is a better way around this).

---

This behaviour was seen when backing up SharePoint files. [Here](https://learn.microsoft.com/en-us/answers/questions/319882/unable-to-download-onenote-file-using-microsoft-gr?orderby=newest) is a thread from Microsoft forums which discusses about 503 when backing up large SharePoint files (~2GB). This seems to be reproducible with test tenants.

**Comment by vkamra** [comment]
Fixed with #2888

**Comment by meain** [comment]
@vkamra I was waiting to maybe add a skip for large OneNote items that give a 503

**Comment by vkamra** [comment]
Ah yes let's please track and do that. I know I stole this ticket from you :) - can you open a new one please?

**Comment by meain** [comment]
Create an issue at https://github.com/alcionai/corso/issues/2910
