### ISSUE TITLE
Don't attempt to load [dir]meta files in RestoreMultipleItems

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#2878]
Newer versions of Corso can load metadata files inline so we don't need to augment the path set during restore. However the logic for this was never updated

Action items:
* remove [dir]meta files from the path set during OneDrive restore for newer versions of Corso

> The paths are not present in the metadata anymore, but they do get added in `AugmentRestorePaths` as we need to inject directory paths inorder to make sure permissions for folders without any files are restored properly. ([ref](https://github.com/alcionai/corso/blob/d1ce661b8fa03805e57b21ea7abcfb75d01a47ac/src/internal/connector/onedrive/restore.go#L643))

**Comment by meain** [comment]
I have a fix for this in https://github.com/alcionai/corso/pull/2908

**Comment by ashmrtn** [comment]
unassigning as this will have a longer timeline if it does get addressed

**Comment by ashmrtn** [comment]
closing as we'll still need to pull these in if we want permission inheritance to work out how we expect
