### ISSUE TITLE
[Bug]: CalendarId shown instead of calendar names in progress

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso#3060]
### What happened?

$ ./corso backup create exchange --user <<user_id>> --retain-progress
Connecting to repository:      1s done
Connecting to M365:         done
Backing Up ∙ <<user_id>>
Discovering items to backup:      8s done
∙ contacts:      0s done
∙ email:      3s done
∙ events:      2s done
Backing up data:      9s ●∙∙
events ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙    2 - AAMkADk1MTI5Mzg3LWM2NWEtNDIyYy04YzM2LTk4MmQyODQ1MTg1NQBGAAAAAACkroLh15brS61qBdQVWICOBwAizZwHWpf_SrrO5GWjW75SAAAAAAEGAAAizZwHWpf_SrrO5GWjW75SAAAJHlsFAAA=
email ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙   20 - Inbox
events ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙●∙∙∙∙∙  141 - AAMkADk1MTI5Mzg3LWM2NWEtNDIyYy04YzM2LTk4MmQyODQ1MTg1NQBGAAAAAACkroLh15brS61qBdQVWICOBwAizZwHWpf_SrrO5GWjW75SAAAAAAEGAAAizZwHWpf_SrrO5GWjW75SAAAJHlsGAAA=

### Corso Version?

unreleased-10d8b9c

### Where are you running Corso?

ubuntu vm

**Comment by ashmrtn** [comment]
closing as duplicate

**Comment by gmatev** [comment]
Dup #3013
