### ISSUE TITLE
Improve how expired download URLs are handled

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#3069]
Currently - when a OneDrive backup is initiated - we do a delta based enumeration and request download URLs for every item (this allows us to not have to call GetDriveItem for every item.

However - these URLs are time limited and if the backup operation takes too long they will expire (request will fail with a 401 error) in which case we call GetItem to get a new download URL.

This should be optimized because it's an extra round trip for every item (to get the 401 and then renew).

Possible options could be:
1) Do not enumerate all items up front - enumerate a batch, process it and then enumerate more - the assumption being that the download URLs will be fresher.
2) Track expiry time for these URLs (or trigger expiry on the first 401) and then assume we need to get new ones (i.e. save the 401 round trip)
3) ~Is there something we can do client side to renew these URLs e.g. get a new access token and update URL?~ Update - not possible
4) A version of (1) will be to do a full delta re-enumeration when we hit a 401. It will be cheaper (in terms of Graph requests/tokens) vs calling GetItem for everything left

**Comment by pandeyabs** [comment]
Re #2, did we also explore [configurable token lifetime(CTL)](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#access-token-lifetime) to extend token lifetime from ~1hr to ~20 hrs?

Although, this may not be ideal from a security standpoint. `Adjusting the lifetime of an access token is a trade-off between improving system performance and increasing the amount of time that the client retains access after the user's account is disabled.`

**Comment by vkamra** [comment]
> Re option 3, did we also explore [configurable token lifetime(CTL)](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#access-token-lifetime) to extend token lifetime to > 1hr ?

I don't believe that applies to these. The download URLs are [generated](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content?view=odsp-graph-online#response) by the backend service and their lifetime isn't configurable

**Comment by pandeyabs** [comment]
Thanks! Let me explore this a bit more. 

> It also looks like this would be a setting in the customer environment and not something Corso would be able to control?

I found [this page ](https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes?source=recommendations#application-policies )which seems to suggest that token lifetime policies can be attached to an application.

Also, clients can apparently request long lived access to resources - [see scope field ](https://learn.microsoft.com/en-us/graph/auth-v2-user#authorization-request)

Let me understand this a bit more and get back to you.

**Comment by pandeyabs** [comment]
Cache integration into restore path is ongoing.
