### ISSUE TITLE
handle context cancellation

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#308]
We're passing around contexts and I believe we said we'd exit early on context cancellation (there's some code scattered here and there for that), but it's not full threaded through the codebase yet

**Comment by gmatev** [comment]
Has this been addressed with some of the the recent context work already?

**Comment by ashmrtn** [comment]
ah, this one was an older issue about handle stuff like ctrl-C gracefully. Usually the pattern is to catch the signal and then cancel the context for the operation. Since we haven't really been focused on that area of things recently we can close this issue
