### ISSUE TITLE
Enable SharePoint permissions backup

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#3135]

**Comment by ashmrtn** [comment]
related to #2528 though not sure how easy it would be to just continue with that PR

**Comment by meain** [comment]
@ryanfkeepers FYI, for [permissions](https://learn.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0), we do not currently track `siteUser` and `siteGroup`. We should probably include that as we are now starting to backup permissions for sharepoint. Also, we currently skip `application` and `device` permissions, as we were previously using email and not id. Now that we have switched to ids I think we can enable them as well as we just have to send back the id.

**Comment by ryanfkeepers** [comment]
@meain Thanks for the heads up.  Added those in https://github.com/alcionai/corso/pull/3311.
