### ISSUE TITLE
Add OneDrive support to `GetUserInfo` API

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#3144]
[GetUserInfo](https://github.com/alcionai/corso/blob/main/src/pkg/services/m365/m365.go#L139) doesn't check whether OneDrive was enabled.

This tracks updating the API (and the `discovery.UserInfo` API it calls) to call https://github.com/alcionai/corso/blob/3e3c16426f7fc12f42034b80ec92642c95224534/src/internal/connector/onedrive/api/drive.go#L214 to check if there are any drives enabled

**Comment by neha-Gupta1** [comment]
Done as part of - https://github.com/alcionai/corso/pull/3106
