### ISSUE TITLE
[Bug]: passing `/` (root) doesn't select anything for backup details

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/corso#3252]
### What happened?

From the documentation, it seems like `/` should match anything under the root. However, when it's passed in nothing is selected. Other prefix matching works (e.x. `/folder`)

### Corso Version?

Corso dev-v0.6.1-209-g96715c272

### Where are you running Corso?

N/A

### Relevant log output

```shell
printing the selector shows

{
  "service": 2,
  "resourceOwners": "Pass"
}
```

**Comment by ashmrtn** [comment]
this also applies to SharePoint

**Comment by neha-Gupta1** [comment]
PR: https://github.com/alcionai/corso/pull/3328
