### ISSUE TITLE
[Bug]: Restored OneDrive items' Direct Access (permissions?) does not appear in webservice.

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#3273]
### What happened?

Repro:
1. login to onedrive.com; go to `my folders`
2. give uses Direct Access to an item (file or folder, does not matter)
3. backup the onedrive account
4. restore the onedrive account
5. in the onedrive webservice, open the restored folder and look for the items to which you previously gave Direct Access.  They will not display those users as having Direct Access.

### Corso Version?

Corso v0.6.1

### Where are you running Corso?

any

**Comment by meain** [comment]
I am not able to repro this with the latest commit (b6ef2d526). Just in case you missed, we don't restore permissions by default and have to pass in the `--restore-permissions` flag to do so.
