### ISSUE TITLE
[Bug]: Contacts folders shown in restore details results

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#3281]
### What happened?

The command `corso restore exchange --backup deadbeef...` (backup only contains contacts) prints out both the restored contact (santiago), as well as the restored contact folder (Contacts).  This is a regression, only the contacts should be displayed in the restore details.

```
Restoring to folder Corso_Restore_02-May-2023_17:37:29
  ID            Contact Name
  74840f9459b1  Sanitago TestContact - 2023-04-28T20:58:44.2865310Z
  ID            Display Name
  4e1276a1b6d9  Contacts
```

### Corso Version?

Corso v0.6.1

### Where are you running Corso?

any

**Comment by ashmrtn** [comment]
I think it should be easy to fix this by using the `Items()` call on the restore details instead of printing all items in the details. This behavior changed when the folder generation logic changed
