### ISSUE TITLE
[Bug]: repoID is empty in backup events

### ISSUE THREAD

**Issue by neha-Gupta1** [alcionai/corso#3388]
### What happened?

repoID is blank/empty in backup start and end events.

### Corso Version?

Corso v0.7.0

### Where are you running Corso?

Local Ubuntu system

**Comment by vkamra** [comment]
Observed pattern was that we get Corso Start/End events _with_ repoIDs but Backup Start/End events *do not* have repoIDs

**Comment by gmatev** [comment]
The relevant recent change is https://github.com/alcionai/corso/pull/3071/files but id does not change where the ID is coming from. In the previous version the repoID was used as userID, but I suspect Rudderstack might be assigning an ID itself in that case so we may not have noticed it before.

**Comment by vkamra** [comment]
@neha-Gupta1  - Adding notes from discussion on this:

- We should add string constants that we initialize the repoID and use to set for error cases (where repoID lookup fails) so it helps to narrow down the issue (e.g. `not_init` , `not_found`) - this will help narrow down what case we're seeing this in
- We should change the code to use the repoID in the config file (similar to what corso_start events do)

**Comment by neha-Gupta1** [comment]
Added a PR- https://github.com/alcionai/corso/pull/3449 for more info

**Comment by vkamra** [comment]
Will close after we do a release and verify.

**Comment by vkamra** [comment]
Need to validate this issue is fixed after the next release - 0.8.0 still had issues

**Comment by neha-Gupta1** [comment]
@gmatev are we still seeing this issue?
