### ISSUE TITLE
Immutable Backups

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#3519]
Leverage S3 object locking/versioning and retention to provide guarantees that backups cannot be removed or tampered with for the specified duration

Additional work on testing:
* #3799

**Comment by vkamra** [comment]
Test

**Comment by ashmrtn** [comment]
non-CLI support for this is done. There's some CLI code that I can push that should be kept hidden but we should use a separate ticket to track that

**Comment by ashmrtn** [comment]
closing this as SDK support has been merged to main
