### ISSUE TITLE
[Bug]: Graph supports contact folder hierarchy, Corso does not

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#3550]
### Issue
According to [graph api documentation](https://learn.microsoft.com/en-us/graph/api/user-post-contactfolders?view=graph-rest-1.0&tabs=http), contact folders are able to express arbitrarily deep folder hierarchies.  However, Corso is built on the assumption that contacts can only express a single-level depth hierarchy.  As a result, it fails to find contacts within nested folders.

### Repro
Within a test user, I created a contact folder hierarchy matching `/contacts/first/second/third/fourth`.  This account already has one contact within /contacts, and I created a second within /fourth.

Graph API calls on postman to `/me/contacts/delta` only return the contact entry in the `/contacts` folder, while `/me/contactfolders/fourth/contacts/delta` contains the new contact.  This matches outlook behavior we expect from hierarchical categories (ie: mail).  

A test backup/details on a new bucket for that user shows corso only backed up the user in the /contacts folder:
```
corso backup details exchange --backup 325e39d7-fd53-481d-9f14-e99aabba653b
	
Connecting to repository:      2s done
  ID            Contact Name
  07ae81a7429c  Sanitago TestContact - 2023-05-31T23:43:29.8797140Z
```

### Expectations
Corso should traverse the complete contacts hierarchy for both backup and restores.

### Changes Needed
* Container enumeration during backup creation should expand to contain all child folders.
* Collection restoration must support a folder hierarchy instead of a single folder.

### Corso Version?

Corso v0.8.0

### Where are you running Corso?

any

**Comment by ryanfkeepers** [comment]
update for changes to the webapp allowing the display of folders: OWA now allows users to view contact folders instead of tags.  This has some interesting conflicts with the hierarchy view. Ex:

<img width="217" alt="image" src="https://github.com/alcionai/corso/assets/104464746/b240b1fc-c3cb-4ea7-b680-5a3b167110a4">

In this image there are four top level folders (Contacts, Corso_Test..., testOWAFolder, and FirstNestedFolder).  The other "*NestedFolder" entries all compose a hierarchy.  EG: second is the child of first, and so on.  The full hierarchy is incorrectly displayed as a flat directory, and the webapp has no ability to create a new folder as a child of another folder.

As a manual test, I created the `testOWAfolder` and populated it with a contact.  That folder and contact were backed-up as expected.

**Comment by ryanfkeepers** [comment]
referencing: https://github.com/alcionai/corso/pull/4478#discussion_r1370503972

**Comment by vkamra** [comment]
Closing this as we haven't seen the ability to create contact folder hierarchy using Outlook/Exchange.
