### ISSUE TITLE
Improve error message when no items found to restore

### ISSUE THREAD

**Issue by meain** [alcionai/corso#3579]
Currently if we try to restore from an empty backup or if the user asks to restore an item not present in the backup, the error that they get is `running restore: primary failure: running restore: producing collections to restore: no restore path given` which is not very useful.

We should probably improve the situation here and let them know what the exact problem is (whether they are trying to restore an empty backup of if we were not able to find the item they requested in the backup) instead of throwing this generic error.

**Comment by vkamra** [comment]
https://github.com/alcionai/corso/pull/3643

**Comment by vkamra** [comment]
@neha-Gupta1 - can this be closed now? #3643 has merged
