### ISSUE TITLE
Add a way to record skips for sub components like an attachment

### ISSUE THREAD

**Issue by meain** [alcionai/corso#3620]
As of now we can only record skipping a complete item and not an individual component like an attachment for an item.
Previous conversation: https://github.com/alcionai/corso/pull/3607#discussion_r1228501229

**Comment by ryanfkeepers** [comment]
closing: we're using `Alert` functionality for this.  If we want a dedicated sub-component skip, we'll need to work with SDK consumers to manage that handling.
