### ISSUE TITLE
Add lint rules

### ISSUE THREAD

**Issue by meain** [alcionai/corso#3654]
Below are a few suggestions for lint rules to be added(and coding practices we follow).

- [x] Prefer `any` instead of `interface{}` [ref](https://github.com/alcionai/corso/pull/3644#discussion_r1235602597)
- [x] Just `)` on the last line of a function call [ref](https://github.com/alcionai/corso/pull/3644#discussion_r1235597340)
- [x] Use `len(...)` instead of `... == ""` or `... != ""` [ref](https://github.com/alcionai/corso/pull/3644#discussion_r1235613027)
- [x] Linter to catch typos in struct tags (eg: josn instead of json) [ref](https://github.com/alcionai/corso/pull/3353#discussion_r1188750791)

**Comment by ryanfkeepers** [comment]
> Prefer any instead of interface{}

I actually tried to do this one with forbid already.  Doesn't work for some reason.  No idea why, but it simply doesn't catch the sequence.  Ashley thinks it might be something with the AST parsing.  I've been wondering if checking for it in usage as a map/slash/func param would work instead.  Ex: `(]|, |\()interface` as the matcher.

> Just ) on the last line of a function call

Haven't tried this one yet, but I'm worried there's no good way to do it and avoid conflicts with const() and var() sets.

> Use len(...) instead of ... == "" or ... != ""

👍 

> Linter to catch typos in struct tags (eg: josn instead of json)

👍

**Comment by ashmrtn** [comment]
I have a linter pretty much written for the tags (it needs a name before I open the repo up). For the interface one, a custom linter may be easiest (if one doesn't already exist)

Also may be worth adding to the list (descriptions from their project pages):
* usestdlibvars - A linter checks the odd number of key and value pairs for common logger libraries
* loggercheck - A linter that detect the possibility to use variables/constants from the Go standard library

both already have support in golangci-lint

**Comment by meain** [comment]
For item 2 (`Just ) on the last line of a function call`), we can probably use `tree-sitter` to look for those patters. One option would be to use something like [tree-grepper](https://github.com/BrianHicks/tree-grepper) and check if `tree-grepper -q go '(argument_list "," .)'` returns anything.
