### ISSUE TITLE
File export from OneDrive backup

### ISSUE THREAD

**Issue by meain** [alcionai/corso#3670]
https://github.com/alcionai/corso-roadmap/issues/43

Ability to export files/foldres from OneDrive directly to local filesystem instead of restoring. SDK users should also be able to extract files through corso.

**Comment by breisig** [comment]
This would be a excellent feature to have.

**Comment by meain** [comment]
> This would be a excellent feature to have.
This is currently being worked on in https://github.com/alcionai/corso/pull/3797. No final timelines yet, but should have something in the coming weeks.

**Comment by meain** [comment]
This is now available in `main`.
