### ISSUE TITLE
Longevity Test Automation

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#3679]
This tracks creating a framework to run longevity tests for Corso.

Current requirements:

Setup:
- Create a longevity test corso repository

Backup:
- Run backup nightly (Exchange, OD, Sharepoint, Teams (in future))
- Use release builds for this (this will guard against any repo corruption for changes that merge into mainline that aren't fully tested)
- Important : Must disable telemetry when using this build to avoid affecting usage stats

Restore:
- TBD (perhaps we wait for Export/DryRun features and enable those))

Backup Deletion:
- Delete any backups older than XXXX days

Maintenance:
- Run quick maintenance every night
- Run full maintenance every week

**Comment by ashmrtn** [comment]
backups should run against a user that has some amount of data churn so we can better exercise the maintenance logic

**Comment by neha-Gupta1** [comment]
@ashmrtn the data here should be fixed( so that we are aware of input provided) or should it be any data that the user have(to make it more inclusive and have wide range of data).

**Comment by ashmrtn** [comment]
we can just use any data the user has for this. These tests are mostly to make sure that over the long run things work as intended. Ideally we'd have a controlled data set, but we also need a fair amount of churn in the data set (so we can track how maintenance behaves). That would require quite a bit of work to setup

**Comment by neha-Gupta1** [comment]
https://github.com/alcionai/corso/pull/3752 covers- setup, backup and maintenance

**Comment by neha-Gupta1** [comment]
Will track restore in - https://github.com/alcionai/corso/issues/3825

**Comment by vkamra** [comment]
Closing this ticket now.
