### ISSUE TITLE
Backup List should display and/or filter with backup data categories

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#3748]
## Issue

For services with multiple data categories (such as Exchange), each backup isolates its categories to the data that was present in the backup.  For example:
```
create backup exchange                                # => b_1
create backup exchange --data contacts    # => b_2
```
In this example, `b_1` contains all categories of data, while `b_2` only contains contacts.  This restriction is opaque to the end user.  It's only discoverable through a a `backup details` call investigating the contents of each backup.  And even then, only indirectly, since the user would have to read the contents of the backup or do a categorical selection.

Exposing the data categories within the backup list would provide much better transparency and help users select appropriate backup ids for details and restoration.

## Acceptance criteria
* Display data categories within a backup in `backup list` entries
* Allow users to list only backups containing a certain data category with the `--data` flag.

**Comment by ashmrtn** [comment]
this goes along well with the idea that we should be tagging backups with the `Reason`s they correspond to
