### ISSUE TITLE
[Bug]: Progress bars off-by-one (or more) causing duplication. 

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#3787]
### What happened?

We're still getting off-by-one copies of progress bar outputs.  Note the double `Connecting` in this example:
```sh
Connecting to repository:      2s done
Connecting to M365:         done
Connecting to M365:         done
Backing Up ∙ https://10rqc2.sharepoint.com/sites/Testing_Bad_ISOs
Discovering items to backup:     30s done
∙ libraries:     30s done
∙ files:     30s done
```

The problem gets especially bad with the use of the `--retain-progress` flag.

### Corso Version?

Corso v0.10.0

### Where are you running Corso?

any

**Comment by vkamra** [comment]
Is a regression in `main` - issue does not exist in `v0.10.0`

**Comment by vkamra** [comment]
Ok - not a progress bar bug - we're calling `ConnectToM365` twice now which is resulting in this. Introduced in 8b8172848865

**Comment by ryanfkeepers** [comment]
I did have a run with many hundreds of duplications.  But that was on a local debugging diff, so I'm not 100% positive I didn't accidentally inject a fmt print.

Before we close this issue out, whomever makes the change to remove the second connect observe should also ensure we're not seeing unwanted duplications when using the `--retain-progress` flag.
