### ISSUE TITLE
[Bug]: Exchange backup fails when user has open shared calendars

### ISSUE THREAD

**Issue by meuchels** [alcionai/corso#3814]
### What happened?

Exchange backup attempts to backup user's open shared calendars.
Then fails with error "Content is Empty"

Expected to not back up shared calendars and only back up personal calendars.

### Corso Version?

Corso unreleased-7fbe03a

### Where are you running Corso?

Ubuntu 22.04 VM to Minio S3 Storage

**Comment by meain** [comment]
Hmm, I was not able to repro this on `7fbe03a`. The full error or logs for this run could be useful in case you have that available. Just the full like of the error message in the log would be of help as well.

In any case, we had a [similar problem](https://github.com/alcionai/corso/issues/3811) that we fixed recently which could if nothing help us give more insights. Could you try running with the latest commit?

**Comment by meuchels** [comment]
[2023-07-15T15-01-08Z.log](https://github.com/alcionai/corso/files/12070480/2023-07-15T15-01-08Z.log)

Here is the log from the latest run using this command.
`corso backup create excahge --config-file $configfile --mailbox 'user@domain.com' --data events --mask-sensitive-data --log-level debug`

**Comment by meuchels** [comment]
unreleased-dd32521 proved same results

**Comment by meuchels** [comment]
doing some more digging i found the calendar that is failing is not the users primary calendar,
it is a secondary calendar that has many reoccurring entries.
Graph explorer times out trying to run a delta scan on that calendar.
Therefore the list to backup is empty, which is probably what is throwing your error.

**Comment by meain** [comment]
> Graph explorer times out trying to run a delta scan on that calendar.

This is very useful information. Thanks for taking the time to dig into it. If Graph itself if not able to give us the details, we might not be able to do much, but let us try a few things first.

- Can we try a non delta variant of the query (`https://graph.microsoft.com/:version/users/:user/calendar/events`)
- Can we try to get lesser number of items from graph by specifying `top=<num>` as a query param
- Can we try to get just the ids instead of the full content of each event in both delta and non delta by specifying `select=id` query param

Also, could you drop the query you are running in Graph explorer here.

**Comment by meuchels** [comment]
eliminating /delta presents events from today forward.
graph does not support $select on deltas
"The following parameters are not supported with change tracking over the 'SyncEvents' resource: '$orderby, $filter, $select, $expand, $search'."

i can use this format
`https://graph.microsoft.com/beta/me/calendars/{calendar-ID}/calendarView/delta?startDateTime=2023-06-01T00:00:00&endDateTime=2023-06-30T00:00:00`

**Comment by ntolia** [comment]
To work around this bug, options were added to Corso to reduce the page size for requests but the problem also disappeared by itself over the weekend. Closing this out for now but we should reopen the issue if we run into this behavior again.
