### ISSUE TITLE
Add explicit 1:1 mapping between snapshots & associated backup models. 

### ISSUE THREAD

**Issue by pandeyabs** [alcionai/corso#3943]
### What happened?

Now that we require assist snapshots to have an associated backup model, we should make the 1:1 mapping between the backup model and the snapshot explicit for both merge & assist backups.

**Changes**
* Don't include merge snapshot in assist snapshots during base selection. This would also need some changes to kopia wrapper.
*  Return `{ManifestEntry, BackupEntry}` tuples for merge bases & assist bases during base selection.

### Corso Version?

Corso v0.11.1

### Where are you running Corso?

NA

### Relevant log output

```shell
NA
```

**Comment by ashmrtn** [comment]
Basic work for separation is done. Some other cleanup can be done to consolidate data fields
