### ISSUE TITLE
Provide CLI support to modify Corso passphrase

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#4061]
The Corso passphrase for a repository can currently only be modified by using the Kopia CLI.

This tracks providing Corso CLI support to do this.

**Comment by ashmrtn** [comment]
[here's](https://github.com/kopia/kopia/blob/1d0f31f32e565ac4f652bc86ec5a22062cabcdf1/cli/command_repository_change_password.go#L25) the kopia CLI code that handles changing passwords. Part of it is custom (or at least partly custom) functions to make sure passwords match etc. We'll need to figure out some way to handle that ourselves perhaps.

The other part is actually changing the password. There's a kopia function that we can call for that

**Comment by vkamra** [comment]
This is in-progress

**Comment by vkamra** [comment]
Done with #4518
