### ISSUE TITLE
Enhancement: pass more than one id to the delete command

### ISSUE THREAD

**Issue by zombiehoffa** [alcionai/corso#4119]
Would be nice to be able to pass more than one ID to the delete command on the cli so that when I'm going through the pain of pulling out ids based on date I can just pass the whole group of backups older than my desired date range to the delete command rather than coding a loop to pass each one individually.

**Comment by vkamra** [comment]
Can leverage #4019

**Comment by neha-Gupta1** [comment]
@zombiehoffa a new flag `backups` has been exposed to handle deletion of multiple IDs by providing `,`(comma) separated backupIDs. 
Currently the functionality is present in latest main. And will be available from release  `v0.14.0`

**Comment by vkamra** [comment]
This is done.
