### ISSUE TITLE
Possible incorrect incremental backups for Groups

### ISSUE THREAD

**Issue by meain** [alcionai/corso#4371]
Backups make use of `canUsePreviousBackup` variable to decide if we should be using the previous backup as a base and do an incremental update or if we should be doing a full backup. This causes issue with the Groups incremental backups as messages and sites can have different value for the value and we might use just the delta update but with the variable set to true. This can be even more dangerous when we have multiple sites being backed up as we might just run into metadata parsing issue just for one site.

Here is a possible scenario where we would end up with an incorrect backup:
- Backing up sites
  - Metadata looks good, so we set `canUsePreviousBackup` to true
  - We only send back incremental set of collections
- Now we try to back up messages
  - Metadata is wrong
  - We set `canUsePreviousMetadata` to false and send back the full collection

In this case, even though `canUsePreviousMetadata` is false at the end of the function, we only have incremental set of collections for sites. This will cause our newer backup to only have the incremental data within in.

Ref:  https://github.com/alcionai/corso/blob/2bd7ee45ddf2eb6d0cf1a02af8931949d1e0a3b8/src/internal/m365/service/groups/backup.go#L31

**Comment by ashmrtn** [comment]
I think ideally we should try to move away from having the additional `canUsePreviousBackup` return value and instead send back collections that delete the root of the hierarchy (and associated subdirectories) if needed. For example, if we were doing a drive backup and found out that the delta token expired we'd send back a collection for path `tenant/service/user/files/drive-id/root` marked with state `DeletedState`

This change can be done bit by bit in the code, but would allow individual control over different data types/instances of a data type
