### ISSUE TITLE
[Bug]: Publish backup stats even if the backup failed or succeeded partially 

### ISSUE THREAD

**Issue by pandeyabs** [alcionai/corso#4765]
### What happened?

Currently we only publish results for successful backups. See [code](https://github.com/alcionai/corso/blob/6307d8cbf6ece36e4afc7e04bb2664f1f95ae865/src/internal/operations/backup.go#L334). 

We should publish stats regardless of the outcome of the backup operation. Otherwise we won't be able to track metrics which got emitted during failed/partial backups.

### Corso Version?

Corso v0.16.0

### Where are you running Corso?

NA

**Comment by ryanfkeepers** [comment]
closing: fixed in https://github.com/alcionai/corso/pull/5016
