### ISSUE TITLE
[Bug]: Groups/Teams backup failure if a group has an empty display name

### ISSUE THREAD

**Issue by Integratinator** [alcionai/corso#4918]
### What happened?

Attempting to backup any groups in a tenant when at least one group has an empty display name results in Error: Failed to retrieve M365 groups: retrieving groups: validating groups: missing display name

Probably due to a similar check as for #4540

### Corso Version?

Corso v0.17.0

### Where are you running Corso?

N/A

**Comment by HiteshRepo** [comment]
Hi @Integratinator Thanks for reporting. Could you please share the command used? Did you opt for all groups backup for the tenant i.e. `corso backup create groups --group '*'`?

**Comment by ntolia** [comment]
@Integratinator So that we can repro this internally, can you also share how you created the group with no display name? Did you use PS or did the admin interface work?

**Comment by Integratinator** [comment]
> Hi @Integratinator Thanks for reporting. Could you please share the command used? Did you opt for all groups backup for the tenant i.e. `corso backup create groups --group '*'`?

Yes, I did a backup of all the groups with the above command. 

I am making a backup of a tenant I do not own, I have no access other than the app registration, so I haven't checked which group is causing it or how it was created. 

I will try to reproduce the problem in my own tenant.

**Comment by ryanfkeepers** [comment]
Hi @Integratinator, thanks again for bringing the issue to our attention.  We're going to relax the rules on groups backups and allow resources to run if they have an empty display name.  I've run some manual tests and things are working just fine without that value present.  You should see this fix in the next release.  Or, if you'd like to try it out manually, I can send you a nightly build containing the update.
