### ISSUE TITLE
Stricter OSS license checks

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#51]
The current OSS license checks merged in https://github.com/alcionai/corso/pull/50 are not strict enough and only fails if one of  the [forbidden](https://github.com/google/licenseclassifier/blob/842c0d70d7027215932deb13801890992c9ba364/license_type.go#L323) licenses is used.

We would like to be stricter and fail the [restricted](https://github.com/google/licenseclassifier/blob/842c0d70d7027215932deb13801890992c9ba364/license_type.go#L176) set as well.

**Comment by gmatev** [comment]
Corso has moved away from License checks in favor of functional verification of whether Exchange, OneDrive, Sharepoint exist for a resource.
