### ISSUE TITLE
Init modelStore backup

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#948]
# Problem
Corso only stores the backup after the operation completes.  Incomplete, cancelled, or erroneous runs do not get recorded.  This prevents a review of system behavior within those situations, and has introduced workarounds for tracking end-to-end operations such as the pre-declaration of model IDs in callers.

# Acceptance Criteria
- [ ] Generate an initial backup entry when a backup operation is started.  Update that entry when the operation concludes.

**Comment by gmatev** [comment]
@ryanfkeepers did #946 completely address this?

**Comment by ryanfkeepers** [comment]
It did not.  946 allows us to generate the _id_ for an entry, but isn't eagerly generating the model store entry itself.

That said, this is out of date, and is likely to be overwritten by concerns involving restartability.  It should probably be closed.
