### ISSUE TITLE
Support folder search when the folder selector is not an absolute path

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#984]
The current behavior for `--<item>-folder` selectors is to do a prefix search based on the selector value i.e. `--email-folder=folderA` will match `/folderA` and any item in it's hierarchy.

As discussed [here](https://github.com/alcionai/corso/pull/979#discussion_r982852900_) - this doesn't allow for folder searches.

The proposal is to change the selector to support the following behavior:

- If a single folder name is specified e.g. `FolderA` - then match any paths that have that folder as one of the path elements. This allows folks to find a specific folder
- If a path is specified - prefix match

This behavior makes sense and would be easy to explain to a user also.

**Comment by ryanfkeepers** [comment]
A possible component of the solution: https://github.com/alcionai/corso/issues/1224

**Comment by ryanfkeepers** [comment]
Completed as part of #1224

**Comment by gmatev** [comment]
@ryanfkeepers should this be marked closed completed?

**Comment by ryanfkeepers** [comment]
Yep, thanks!
